# 제로베이스 데이터 사이언스 스쿨 3기 SQL 과제 2
- 유가 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 30점
- 5번 10점
- 6번 10점
- 7번 15점
- 8번 15점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

---

In [124]:
import mysql.connector
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import re
import numpy as np
from tqdm import tqdm
import googlemaps

문제 1.

주유소 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

```
create table GAS_BRAND(
    id int not null auto_increment,
    name varchar(16),
    primary key (id)
);

create table GAS_STATION(
    id int not null auto_increment,
    brand int,
    name varchar(32),
    city char(2),
    gu varchar(10),
    address varchar(128),
    gasoline int,
    diesel 
    self BOOL,int,
    car_wash BOOL,
    charging_station BOOL,
    car_maintenance BOOL,
    convenience_store BOOL,
    24_hour BOOL,
    lat DECIMAL(16,14),
    lng decimal(17,14),
    primary key (id),
    constraint oil foreign key (brand) references GAS_BRAND(id)
);
```

문제 2.

Python 코드로 GAS_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

In [70]:
remote = mysql.connector.connect(
    host = 'database-1.cfc20ugqgb4j.ap-northeast-2.rds.amazonaws.com',
    port = 3306,
    user = 'oneday',
    password = '1234',
    database = 'oneday'
)

In [74]:
cur = remote.cursor()
sql = open('oil3.sql', encoding='UTF8').read()

In [75]:
for  result_iterator in cur.execute(sql, multi=True):
    if result_iterator.with_rows:
        print(result_iterator.fetchall())
    else:
        print(result_iterator.statement)

insert into GAS_BRAND VALUES (1, 'SK에너지')
insert into GAS_BRAND VALUES (2, '현대오일뱅크')
insert into GAS_BRAND VALUES (3, 'GS칼텍스')
insert into GAS_BRAND VALUES (4, 'S-OIL')
insert into GAS_BRAND VALUES (5, '알뜰주유소')
insert into GAS_BRAND VALUES (6, '자가상표')

In [76]:
remote.commit()
remote.close()

제출 1.
- Table 생성 결과 : Desc GAS_BRAND; Desc GAS_STATION;

```
+-------+-------------+------+-----+---------+----------------+
| Field | Type        | Null | Key | Default | Extra          |
+-------+-------------+------+-----+---------+----------------+
| id    | int         | NO   | PRI | NULL    | auto_increment |
| name  | varchar(16) | YES  |     | NULL    |                |
+-------+-------------+------+-----+---------+----------------+

+-------------------+----------------+------+-----+---------+----------------+
| Field             | Type           | Null | Key | Default | Extra          |
+-------------------+----------------+------+-----+---------+----------------+
| id                | int            | NO   | PRI | NULL    | auto_increment |
| brand             | int            | YES  | MUL | NULL    |                |
| name              | varchar(32)    | YES  |     | NULL    |                |
| city              | char(2)        | YES  |     | NULL    |                |
| gu                | varchar(10)    | YES  |     | NULL    |                |
| address           | varchar(128)   | YES  |     | NULL    |                |
| gasoline          | int            | YES  |     | NULL    |                |
| diesel            | int            | YES  |     | NULL    |                |
| car_wash          | tinyint(1)     | YES  |     | NULL    |                |
| charging_station  | tinyint(1)     | YES  |     | NULL    |                |
| car_maintenance   | tinyint(1)     | YES  |     | NULL    |                |
| convenience_store | tinyint(1)     | YES  |     | NULL    |                |
| 24_hour           | tinyint(1)     | YES  |     | NULL    |                |
| lat               | decimal(16,14) | YES  |     | NULL    |                |
| lng               | decimal(17,14) | YES  |     | NULL    |                |
+-------------------+----------------+------+-----+---------+----------------+

```

제출 2.
- GAS_BRAND 조회 결과 : SELECT * FROM GAS_BRAND;

```
+----+--------------+
| id | name         |
+----+--------------+
|  1 | SK에너지     |
|  2 | 현대오일뱅크 |
|  3 | GS칼텍스     |
|  4 | S-OIL        |
|  5 | 알뜰주유소   |
|  6 | 자가상표     |
+----+--------------+
```

문제 3.

다음의 함수와 그 함수를 테스트하는 코드를 작성하세요. (PDF 파일 참고)

- 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
- 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’)
- 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
- 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)

제출 3.
- 각 함수 및 테스트 코드와 실행결과

In [125]:
gmaps_key = 'AIzaSyDS8JfW9b9Fc_DasLH4INDxCoy8aU79UfA'
gmaps = googlemaps.Client(key=gmaps_key)

In [26]:
# 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
def remove_commas(number_str):
    # 숫자 문자열에서 ',' 제거
    result = number_str.replace(',', '')
    return int(result)

remove_commas('1,000')

1000

In [53]:
#주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’)
def brand_search(n):
    if n == 'SK에너지':
        return 1

    elif n == 'HD현대오일뱅크':
        return 2

    elif n == 'GS칼텍스':
        return 3

    elif n == 'S-OIL':
        return 4

    elif n == '알뜰주유소':
        return 5

    else:
        return 6

brand_search('SK에너지')

1

In [28]:
# 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
def split_adr(n):
    tmp  = re.split(' ', n)
    return tmp[1]
split_adr('서울시 강남구 헌릉로 730')

'강남구'

In [29]:
# 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
def get_lat_lng(n):
    tmp = gmaps.geocode(n, language='ko')
    lat = tmp[0].get('geometry')['location']['lat']
    lat = round(lat, 7)
    lng = tmp[0].get('geometry')['location']['lng']
    lng = round(lng, 7)
    return lat, lng

get_lat_lng('서울시 강남구 헌릉로 730')

(37.4665675, 127.1190803)

문제 4.

Python 코드에서 주유소 페이지에서 데이터를 가져올때, GAS_STATION 테이블에 바로 입력하도록 수정하세요. (앞서 생 성한 함수활용)
- 주의. city 는 ‘서울’ 로 고정, 부가정보 데이터 타입
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다. - 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.


제출 4.
- 주유소 데이터 관련 코드 (ipynb)

In [32]:
url = "https://www.opinet.co.kr/searRgSelect.do"
driver = webdriver.Chrome(executable_path="../../eda/driver/chromedriver.exe")
driver.get(url)

In [33]:
# 세차장 경정비 편의점 24시간 태그
driver.find_element(By.CSS_SELECTOR, '#CWSH_YN').click()
driver.find_element(By.CSS_SELECTOR, '#MAINT_YN').click()
driver.find_element(By.CSS_SELECTOR, '#CVS_YN').click()
driver.find_element(By.CSS_SELECTOR, '#SEL24_YN').click()

In [34]:
sido_list_raw = driver.find_element(By.ID, "SIDO_NM0")
sido_list = sido_list_raw.find_elements(By.TAG_NAME, "option")

sido_names = []
sido_names = [option.get_attribute("value") for option in sido_list]
sido_names = sido_names[1:]

In [35]:
gu_list_raw = driver.find_element(By.ID, "SIGUNGU_NM0")
gu_list = gu_list_raw.find_elements(By.TAG_NAME, "option")

gu_names = [option.get_attribute("value") for option in gu_list]
gu_names = gu_names[1:]

In [36]:
element = gu_list_raw = driver.find_element(By.ID, "SIGUNGU_NM0")
element.send_keys(gu_names[1])

In [37]:
driver.find_element(By.CSS_SELECTOR, '#body1 > tr:nth-child(1) > td.rlist > a').click()

In [39]:
req = driver.page_source
soup = BeautifulSoup(req, 'html.parser')

In [77]:
# id
n = 1

In [54]:
# 브랜드 명
brand_search(soup.select_one("#poll_div_nm").text)

2

In [40]:
# 주유소명
soup.select_one("#os_nm").text

'재건에너지 재정제2주유소 고속셀프지점'

In [59]:
city = '서울'

In [45]:
# 구
gu = split_adr(soup.select_one("#rd_addr").text)
gu

'강동구'

In [41]:
# 주소
soup.select_one("#rd_addr").text

'서울특별시 강동구  천호대로 1246 (둔촌제2동)'

In [47]:
# 휘발유
remove_commas(soup.select_one("#b027_p").text)

1559

In [46]:
# 경유
remove_commas(soup.select_one("#d047_p").text)

1469

In [63]:
# 셀프 여부
if soup.find('img', {'alt': '셀프주유소', 'class': 'bul'}):
    print(1)
else:
    print(0)

1

In [64]:
# 새차 충전 경정비 편의점 24시 
if "off" in soup.select_one("#cwsh_yn").get('src'):
    print(1)
else:
    print(0)

0

In [55]:
# 위도 경도
get_lat_lng(soup.select_one("#rd_addr").text)

(37.5365133, 127.1493588)

```
mysql bool 데이터 처리 방법
https://medium.com/daangn/mysql-boolean-%EC%BB%AC%EB%9F%BC-7abd9b35c664
```

In [96]:
conn = mysql.connector.connect(
    host = 'database-1.cfc20ugqgb4j.ap-northeast-2.rds.amazonaws.com',
    port = 3306,
    user = 'oneday',
    password = '1234',
    database = 'oneday'
)

In [91]:
cursor = conn.cursor(buffered=True)

In [92]:
sql = 'insert into GAS_STATION values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'

In [93]:
# 오류발생시 초기화
n = 1

In [94]:
for gu in gu_names:
    element = gu_list_raw = driver.find_element(By.ID, "SIGUNGU_NM0")
    element.send_keys(gu)
    search_result = int(driver.find_element_by_css_selector("#totCnt").text)
    
    for i in range(1, search_result +1):
        driver.find_element_by_css_selector(f'#body1 > tr:nth-child({i}) > td.rlist > a').click()
        html = driver.page_source
        soup = BeautifulSoup(html,"html.parser")
        
        # 초기화
        datas = []
        # id
        datas.append(n)
        # 브랜드명
        datas.append(brand_search(soup.select_one("#poll_div_nm").text))  
        # 주유소명
        datas.append(soup.select_one("#os_nm").text)
        # 서울
        datas.append(city)
        # 구
        datas.append(split_adr(soup.select_one("#rd_addr").text))
        # 주소
        datas.append(soup.select_one("#rd_addr").text)

        # 휘발유
        datas.append(remove_commas(soup.select_one("#b027_p").text))
        # 경유
        if soup.select_one("#d047_p").text == '':
            datas.append(0)
        else:
            datas.append(remove_commas(soup.select_one("#d047_p").text))
        
        # 셀프여부
        if soup.find('img', {'alt': '셀프주유소', 'class': 'bul'}):
            datas.append(1)
        else:
            datas.append(0)
        # 세차장
        if "off" in soup.select_one("#cwsh_yn").get('src'):
            datas.append(0)
        else:
            datas.append(1)
        # 충전소
        if "off" in soup.select_one("#lpg_yn").get('src'):
            datas.append(0)
        else:
            datas.append(1)
        # 경정비
        if "off" in soup.select_one("#maint_yn").get('src'):
            datas.append(0)
        else:
            datas.append(1)
        # 편의점
        if "off" in soup.select_one("#cvs_yn").get('src'):
            datas.append(0)
        else:
            datas.append(1)
        # 24시간
        if "off" in soup.select_one("#sel24_yn").get('src'):
            datas.append(0)
        else:
            datas.append(1)

        # 위도 경도
        tmp = get_lat_lng(soup.select_one("#rd_addr").text)
        lat = tmp[0]
        lng = tmp[1]
        datas.append(lat)
        datas.append(lng)
        cursor.execute(sql, tuple(datas))
        print(tuple(datas))
        conn.commit() 
        time.sleep(0.5)
        n += 1

(1, 1, '(주)보성 세곡주유소', '서울', '강남구', '서울 강남구  헌릉로 731 (세곡동)', 1559, 1469, 1, 1, 0, 0, 0, 0, 37.4671565, 127.1187081)
(2, 2, 'HD현대오일뱅크㈜직영 산성셀프주유소', '서울', '강남구', '서울 강남구 헌릉로 730', 1574, 1494, 1, 1, 0, 0, 0, 0, 37.4665675, 127.1190803)
(3, 1, '자곡셀프주유소', '서울', '강남구', '서울 강남구 밤고개로 120 (자곡동)', 1598, 1559, 1, 1, 0, 0, 0, 0, 37.4834002, 127.1040458)
(4, 4, '극동유화㈜ 개나리주유소', '서울', '강남구', '서울 강남구 언주로 423 (역삼동)', 1615, 1535, 1, 1, 0, 1, 0, 1, 37.5000776, 127.0385419)
(5, 3, '방죽주유소', '서울', '강남구', '서울 강남구 밤고개로 215 (율현동)', 1617, 1539, 1, 1, 0, 0, 0, 0, 37.4749926, 127.1068866)
(6, 2, 'HD현대오일뱅크㈜직영 도곡셀프주유소', '서울', '강남구', '서울 강남구  남부순환로 2718 (도곡2동)', 1619, 1539, 1, 1, 0, 1, 0, 0, 37.4854623, 127.0432181)
(7, 1, '오일프러스 셀프', '서울', '강남구', '서울 강남구 남부순환로 2651 (도곡동)', 1625, 1545, 1, 1, 0, 1, 0, 1, 37.485839, 127.0396721)
(8, 2, '삼성동주유소', '서울', '강남구', '서울 강남구 테헤란로 619 (삼성동)', 1635, 1565, 1, 1, 0, 0, 0, 0, 37.5098576, 127.0651101)
(9, 2, 'HD현대오일뱅크㈜직영 유진주유소', '서울', '강남구', '서울 강남구 논현로 152 (도곡동)', 1639, 1564, 0, 1, 0, 1, 0, 0, 37.4874316, 127.0399976)
(10, 1, '(주)중앙에너비스 수서지점', '서울', '강남구', '서울 강남구 광평로 202 (수서동)', 1657, 1597, 1, 1, 0, 0, 0, 0, 37.4841053, 127.0950401)
(11, 1, '대교셀프주유소', '서울', '강남구', '서울 강남구 강남대로 640 (신사동)', 1680, 1650, 1, 0, 0, 0, 0, 1, 37.5281292, 127.0355537)
(12, 1, 'SK서광주유소', '서울', '강남구', '서울 강남구 역삼로 142', 1685, 1615, 1, 1, 0, 1, 0, 1, 37.4943424, 127.0350915)
(13, 4, '(주)선진도곡주유소', '서울', '강남구', '서울 강남구 도곡로 162 (도곡동)', 1698, 1615, 0, 1, 0, 1, 0, 0, 37.4878254, 127.0466876)
(14, 1, 'SK에너지㈜ 진달래주유소', '서울', '강남구', '서울 강남구 도곡로 208', 1699, 1615, 0, 1, 0, 0, 0, 0, 37.492295, 127.0418598)
(15, 3, '지에스칼텍스㈜에너지플러스허브GS타워', '서울', '강남구', '서울 강남구 논현로 516 (역삼동)', 1709, 1679, 1, 0, 0, 1, 0, 1, 37.5027083, 127.0363956)
(16, 1, '(유)동하석유 힐탑셀프주유소', '서울', '강남구', '서울 강남구 논현로 640', 1737, 1697, 1, 1, 0, 0, 0, 1, 37.5106887, 127.0325689)
(17, 1, '대동석유 압구정주유소', '서울', '강남구', '서울 강남구 언주로 842 (신사동)', 1747, 1697, 1, 1, 0, 0, 0, 1, 37.5253431, 127.0338242)
(18, 3, '대양산업(주) 개포주유소', '서울', '강남구', '서울 강남구 양재대로 339', 1788, 0, 1, 1, 0, 0, 0, 0, 37.4722409, 127.0515134)
(19, 3, '지에스칼텍스㈜ 삼성로주유소', '서울', '강남구', '서울 강남구 삼성로 563 (삼성동)', 1864, 1839, 1, 1, 0, 0, 0, 1, 37.513975, 127.0561274)
(20, 2, 'HD현대오일뱅크㈜직영 신사현대주유소', '서울', '강남구', '서울 강남구 도산대로 163 (신사동)', 1878, 1834, 0, 1, 0, 0, 0, 0, 37.5195205, 127.0263171)
(21, 3, '지에스칼텍스㈜ 은마주유소', '서울', '강남구', '서울 강남구 영동대로 235', 1884, 1792, 0, 1, 0, 1, 0, 1, 37.5000721, 127.0672848)
(22, 3, '대성석유(주)동호주유소', '서울', '강남구', '서울 강남구 봉은사로113길 51', 1929, 1822, 0, 1, 0, 0, 0, 0, 37.518486, 127.0646655)
(23, 3, '지에스칼텍스(주)학여울주유소', '서울', '강남구', '서울 강남구 남부순환로 3170 (일원2동)', 2015, 1940, 0, 1, 0, 0, 0, 0, 37.4946762, 127.0778305)
(24, 2, 'HD현대오일뱅크㈜직영 한양주유소', '서울', '강남구', '서울 강남구 압구정로 302 (신사동)', 2083, 2026, 0, 1, 0, 0, 0, 0, 37.5288681, 127.0341046)
(25, 4, '명품주유소', '서울', '강남구', '서울 강남구 도곡로 249 (역삼동)', 2128, 2037, 1, 1, 0, 0, 0, 1, 37.4942704, 127.0455093)
(26, 3, '(주)소모 쎈트럴주유소', '서울', '강남구', '서울 강남구 삼성로 335', 2147, 2072, 0, 1, 0, 0, 0, 0, 37.5014209, 127.0591408)
(27, 1, '대청주유소', '서울', '강남구', '서울 강남구 개포로 654 (일원동)', 2195, 2086, 0, 1, 0, 0, 0, 0, 37.4924737, 127.085679)
(28, 2, '㈜새서울석유 새서울주유소', '서울', '강남구', '서울 강남구 압구정로 154', 2198, 2098, 0, 1, 0, 0, 0, 1, 37.525835, 127.0265422)
(29, 1, 'SK논현주유소', '서울', '강남구', '서울 강남구 논현로 747 (논현동)', 2395, 2295, 0, 1, 0, 1, 0, 1, 37.5186368, 127.028238)
(30, 2, '(주)제이제이네트웍스 제이제이주유소', '서울', '강남구', '서울 강남구 언주로 716', 2490, 2380, 0, 1, 0, 0, 0, 1, 37.5176472, 127.0357349)
(31, 3, '(주)만정에너지 삼보주유소', '서울', '강남구', '서울 강남구 봉은사로 433 (삼성동)', 2598, 2560, 0, 1, 0, 0, 0, 0, 37.5115207, 127.0471716)
(32, 2, '재건에너지 재정제2주유소 고속셀프지점', '서울', '강동구', '서울특별시 강동구  천호대로 1246 (둔촌제2동)', 1559, 1469, 1, 1, 0, 0, 0, 0, 37.5365133, 127.1493588)
(33, 3, '대성석유(주)길동주유소', '서울', '강동구', '서울 강동구 천호대로 1168', 1636, 1558, 0, 1, 0, 0, 0, 0, 37.5334229, 127.1411725)
(34, 3, '(주)소모 신월주유소', '서울', '강동구', '서울 강동구 양재대로 1323 (성내동)', 1656, 1578, 1, 1, 0, 0, 0, 0, 37.5304933, 127.128992)
(35, 3, '(주)삼표에너지 고덕주유소', '서울', '강동구', '서울 강동구 고덕로 39 (암사동)', 1665, 1585, 1, 1, 0, 0, 1, 0, 37.555049, 127.1297929)
(36, 1, '방아다리주유소', '서울', '강동구', '서울 강동구 동남로 811 (명일동)', 1665, 1575, 1, 1, 0, 0, 0, 0, 37.5490445, 127.1508229)
(37, 1, 'sk해뜨는주유소', '서울', '강동구', '서울 강동구  상일로 132 (강일동)', 1699, 1609, 1, 1, 0, 1, 0, 0, 37.5545085, 127.1724154)
(38, 3, '(주)소모 성내주유소', '서울', '강동구', '서울 강동구 올림픽로 578 (성내동)', 1708, 1608, 1, 1, 0, 1, 0, 0, 37.5313782, 127.1273286)
(39, 4, '(주)퍼스트오일 코알라주유소', '서울', '강동구', '서울특별시 강동구  올림픽로 556 (성내동)', 1710, 1610, 1, 1, 0, 0, 0, 0, 37.5293808, 127.1224408)
(40, 3, '지에스칼텍스㈜ 동서울주유소', '서울', '강동구', '서울 강동구 천호대로 1456 (상일동)', 1711, 1639, 1, 1, 0, 0, 0, 0, 37.5511028, 127.1696401)
(41, 1, '주)지유에너지직영 오렌지주유소', '서울', '강동구', '서울 강동구 성안로 102 (성내동)', 1754, 1654, 0, 1, 0, 1, 0, 0, 37.532314, 127.1331781)
(42, 2, '천호현대주유소', '서울', '강동구', '서울 강동구 천중로 67 (천호동)', 1843, 1743, 0, 1, 0, 1, 0, 0, 37.5451331, 127.129473)
(43, 4, '광성주유소', '서울', '강동구', '서울 강동구 올림픽로 673 (천호동)', 1968, 1858, 0, 1, 0, 1, 0, 1, 37.5416117, 127.1241731)
(44, 1, '북서울고속주유소', '서울', '강북구', '서울 강북구 삼양로 410 (수유동)', 1510, 1434, 1, 0, 0, 0, 0, 1, 37.6401448, 127.017205)
(45, 3, '수유동주유소', '서울', '강북구', '서울 강북구 도봉로 395 (수유동)', 1510, 1434, 1, 1, 0, 0, 0, 1, 37.6421556, 127.0295862)
(46, 1, 'SK에너지(주) 매일주유소', '서울', '강북구', '서울 강북구 삼양로 217 (미아동)', 1535, 1455, 1, 1, 0, 0, 1, 0, 37.6227977, 127.0191356)
(47, 4, '씨앤에스유통㈜ 미아셀프주유소', '서울', '강북구', '서울 강북구 도봉로 200 (미아동)', 1545, 1455, 1, 1, 0, 0, 0, 0, 37.6265292, 127.0265002)
(48, 1, '에덴주유소', '서울', '강북구', '서울 강북구 월계로 195 (번동)', 1545, 1465, 1, 1, 0, 1, 0, 0, 37.6216958, 127.0455344)
(49, 4, '덕릉로주유소', '서울', '강북구', '서울 강북구 덕릉로 158 (번동)', 1545, 1455, 1, 1, 0, 0, 0, 0, 37.6349756, 127.0313182)
(50, 3, '㈜지에스이앤알 미아주유소', '서울', '강북구', '서울 강북구 도봉로 122 (미아동)', 1555, 1459, 1, 1, 0, 0, 0, 0, 37.6199964, 127.0290304)
(51, 3, '대성석유(주)신광주유소', '서울', '강북구', '서울 강북구 삼양로 484', 1559, 1479, 0, 1, 0, 1, 0, 0, 37.6464088, 127.0153285)
(52, 2, 'HD현대오일뱅크㈜직영 번동셀프주유소', '서울', '강북구', '서울 강북구 한천로 963 (번동)', 1577, 1497, 1, 1, 0, 1, 0, 1, 37.6355872, 127.0330493)
(53, 1, '세원주유소', '서울', '강북구', '서울 강북구 한천로 918 (번동)', 1578, 1498, 1, 1, 0, 0, 0, 0, 37.6342596, 127.037732)
(54, 1, '강서오곡셀프주유소', '서울', '강서구', '서울 강서구 벌말로 254 (오곡동)', 1493, 1409, 1, 1, 0, 0, 0, 1, 37.5539622, 126.7684275)
(55, 5, '목화주유소', '서울', '강서구', '서울 강서구 국회대로 251 (화곡동)', 1495, 1424, 1, 1, 0, 0, 0, 0, 37.5300403, 126.8629825)
(56, 2, '행촌에너지 공항주유소', '서울', '강서구', '서울 강서구 개화동로 420 (개화동)', 1495, 1443, 1, 1, 0, 1, 1, 1, 37.574611, 126.8023029)
(57, 4, '스카이주유소', '서울', '강서구', '서울 강서구 개화동로 457 (방화동)', 1495, 1443, 1, 1, 0, 0, 1, 1, 37.5714858, 126.8043806)
(58, 2, '이케이에너지(주) 강서주유소', '서울', '강서구', '서울 강서구 화곡로 273 (화곡동)', 1504, 1422, 1, 1, 0, 1, 0, 0, 37.549163, 126.8469964)
(59, 5, '화곡역주유소', '서울', '강서구', '서울 강서구 강서로 154 (화곡동)', 1504, 1422, 1, 0, 0, 0, 0, 1, 37.5407186, 126.8415303)
(60, 3, '지에스칼텍스㈜ 경인고속주유소', '서울', '강서구', '서울 강서구 국회대로 225 (화곡동)', 1505, 1434, 1, 1, 1, 1, 0, 1, 37.5296209, 126.859797)
(61, 5, '뉴신정주유소', '서울', '강서구', '서울 강서구 곰달래로 207 (화곡동)', 1506, 1424, 0, 0, 0, 1, 0, 0, 37.5315796, 126.8560524)
(62, 1, 'KH에너지(주)직영 KH외발산주유소', '서울', '강서구', '서울 강서구 방화대로 30', 1550, 1480, 1, 1, 1, 1, 1, 0, 37.5434208, 126.816863)
(63, 2, '현대오일뱅크 등촌주유소', '서울', '강서구', '서울 강서구 등촌로 189 (등촌동)', 1576, 1496, 0, 1, 0, 0, 0, 0, 37.546808, 126.8625545)
(64, 1, '개화주유소', '서울', '강서구', '서울 강서구 양천로 57', 1577, 1517, 1, 1, 0, 0, 0, 0, 37.5735014, 126.8100943)
(65, 2, 'HD현대오일뱅크㈜직영 양화교셀프주유소', '서울', '강서구', '서울 강서구 공항대로 653', 1579, 1524, 1, 1, 0, 0, 0, 0, 37.5473368, 126.8774764)
(66, 4, '하이웨이주유소', '서울', '강서구', '서울특별시 강서구 공항대로 432(화곡동)', 1579, 1514, 1, 1, 0, 0, 1, 1, 37.5546677, 126.8548053)
(67, 4, '(주)한진 김포공항주유소', '서울', '강서구', '서울 강서구 하늘길 259', 1590, 1530, 1, 1, 0, 0, 0, 0, 37.5507763, 126.8155549)
(68, 4, '신화곡주유소', '서울', '강서구', '서울 강서구 국회대로 71', 1595, 1495, 1, 1, 0, 0, 0, 0, 37.5272579, 126.8428896)
(69, 1, '화곡현대주유소', '서울', '강서구', '서울 강서구 강서로 151 (화곡동)', 1596, 1566, 1, 1, 0, 0, 0, 1, 37.5402614, 126.8411983)
(70, 3, '대성석유(주) 관문주유소', '서울', '강서구', '서울 강서구 공항대로 314', 1598, 1578, 0, 1, 0, 1, 0, 0, 37.5577232, 126.8425243)
(71, 3, '강서열린주유소', '서울', '강서구', '서울 강서구 등촌로 213 (등촌동)', 1598, 1528, 0, 1, 0, 0, 0, 0, 37.548712, 126.8630628)
(72, 2, 'HD현대오일뱅크㈜직영 가양주유소', '서울', '강서구', '서울 강서구  양천로 391 (가양동)', 1599, 1559, 0, 1, 0, 0, 0, 0, 37.5678802, 126.8510787)
(73, 3, '대성석유(주)방화대성주유소', '서울', '강서구', '서울 강서구 양천로 176', 1616, 1578, 1, 1, 0, 0, 1, 0, 37.5728815, 126.8234821)
(74, 3, '대성주유소', '서울', '강서구', '서울 강서구 강서로 472', 1638, 1598, 0, 1, 0, 1, 0, 0, 37.5675028, 126.8414186)
(75, 1, 'SK KH에너지 가양주유소', '서울', '강서구', '서울 강서구 강서로 498 (가양동)', 1638, 1598, 0, 1, 0, 1, 1, 1, 37.5697823, 126.8419022)
(76, 1, '세원제1주유소', '서울', '강서구', '서울 강서구 양천로 311 (가양동)', 1648, 1598, 1, 1, 0, 1, 0, 0, 37.5678802, 126.8510787)
(77, 3, '박물관주유소', '서울', '강서구', '서울 강서구 양천로53길 97 (가양동)', 1678, 1638, 0, 1, 0, 1, 1, 0, 37.5657849, 126.8451216)
(78, 1, '코리나(주)청룡주유소', '서울', '강서구', '서울 강서구 양천로 576', 1698, 1638, 0, 1, 0, 0, 0, 0, 37.5567325, 126.862765)
(79, 4, '참솔에너지', '서울', '강서구', '서울 강서구 벌말로 281 (오곡동)', 1798, 1698, 1, 1, 0, 0, 0, 0, 37.5562519, 126.7684491)
(80, 1, '염창동주유소', '서울', '강서구', '서울 강서구 양천로 720 (염창동)', 1935, 1860, 0, 1, 0, 0, 0, 0, 37.5491113, 126.8757906)
(81, 2, 'HD현대오일뱅크㈜직영 문성골주유소', '서울', '관악구', '서울 관악구 문성로 97 (신림동)', 1559, 1464, 0, 1, 0, 0, 0, 0, 37.4777941, 126.9143022)
(82, 5, '(주)연우에너지 신관주유소', '서울', '관악구', '서울 관악구 신림로 290 (신림동)', 1565, 1465, 1, 1, 0, 0, 0, 0, 37.480413, 126.9306665)
(83, 1, '(주)한유에너지행운셀프주유소', '서울', '관악구', '서울 관악구 남부순환로 1883 (봉천동)', 1565, 1465, 1, 1, 0, 0, 0, 0, 37.4791083, 126.9591697)
(84, 3, '서일석유(주)락성주유소', '서울', '관악구', '서울 관악구 남부순환로 1920 (봉천동)', 1575, 1475, 1, 1, 0, 1, 0, 1, 37.4771792, 126.9623883)
(85, 1, '대양석유(주)직영 보라매주유소', '서울', '관악구', '서울 관악구  보라매로 26 (봉천동)', 1575, 1475, 1, 1, 0, 0, 0, 0, 37.4916874, 126.9271603)
(86, 1, 'SK에너지(주) 신봉천', '서울', '관악구', '서울 관악구 남부순환로 1880 (봉천동)', 1585, 1485, 0, 1, 0, 0, 1, 0, 37.4787572, 126.9583432)
(87, 1, 'SK에너지(주)직영 대공원주유소', '서울', '관악구', '서울 관악구 과천대로 921 (남현동)', 1585, 1485, 0, 1, 0, 1, 1, 0, 37.4728556, 126.9821515)
(88, 4, '유림주유소', '서울', '관악구', '서울 관악구 신림로 176 (신림동)', 1598, 1498, 0, 1, 0, 1, 0, 1, 37.4737247, 126.93488)
(89, 4, '관악시몬주유소', '서울', '관악구', '서울특별시 관악구 남부순환로 1753 (봉천동)', 1695, 1595, 0, 1, 0, 0, 0, 0, 37.4823585, 126.945101)
(90, 3, 'CJ대한통운㈜ 신림주유소', '서울', '관악구', '서울 관악구 남부순환로 1515 (신림동)', 1748, 1668, 0, 1, 0, 0, 0, 0, 37.4829496, 126.9189553)
(91, 2, 'HD현대오일뱅크㈜직영 능동주유소', '서울', '광진구', '서울 광진구 천호대로 584 (능동)', 1529, 1445, 1, 1, 0, 1, 0, 1, 37.5555551, 127.082455)
(92, 2, '태양주유소', '서울', '광진구', '서울 광진구 동일로 345 (중곡동)', 1534, 1454, 0, 0, 0, 0, 0, 1, 37.563544, 127.0888304)
(93, 2, '(주)창원CW', '서울', '광진구', '서울 광진구 광나루로 460 (화양동)', 1539, 1455, 1, 1, 0, 0, 0, 0, 37.5451042, 127.0804969)
(94, 1, '(주)장수주유소', '서울', '광진구', '서울 광진구 동일로 266 (군자동)', 1547, 1467, 1, 0, 0, 1, 0, 1, 37.5549721, 127.0715197)
(95, 2, 'HD현대오일뱅크㈜직영 중원셀프주유소', '서울', '광진구', '서울 광진구 동일로 398 (중곡동)', 1548, 1469, 1, 1, 0, 0, 0, 0, 37.563544, 127.0888304)
(96, 2, 'HD현대오일뱅크㈜직영 중곡현대주유소', '서울', '광진구', '서울 광진구 동일로 435 (중곡동)', 1548, 1469, 1, 1, 0, 0, 0, 0, 37.5609412, 127.0957458)
(97, 2, 'HD현대오일뱅크㈜직영 장호셀프주유소', '서울', '광진구', '서울 광진구 자양로 37 (자양동)', 1548, 1475, 1, 1, 0, 1, 0, 0, 37.5312783, 127.0858325)
(98, 4, '정해네트웍스(주)일진주유소', '서울', '광진구', '서울 광진구 동일로 413 (중곡동)', 1567, 1487, 1, 1, 0, 0, 0, 1, 37.563544, 127.0888304)
(99, 4, '삼호주유소', '서울', '광진구', '서울 광진구 천호대로 809 (광장동)', 1697, 1597, 1, 1, 0, 0, 0, 1, 37.5456356, 127.1037341)
(100, 1, '유니스에너지 자양주유소', '서울', '광진구', '서울 광진구 아차산로 298 (자양동)', 1698, 1598, 0, 1, 0, 0, 0, 1, 37.531692, 127.074516)
(101, 1, '강평주유소 ㈜강평텔레콤', '서울', '광진구', '서울 광진구 아차산로 616', 1798, 1697, 0, 1, 0, 0, 0, 0, 37.5476119, 127.1072051)
(102, 1, '서서울고속주유소', '서울', '구로구', '서울 구로구 경인로 150 (오류동)', 1490, 1415, 1, 1, 0, 0, 0, 1, 37.4916751, 126.8428418)
(103, 2, '㈜자연에너지 고척주유소', '서울', '구로구', '서울 구로구 고척로 199 (고척동)', 1490, 1415, 1, 1, 0, 0, 0, 0, 37.5051273, 126.8554406)
(104, 4, '씨앤에스유통(주) 구로드림주유소', '서울', '구로구', '서울 구로구 경인로 41 (온수동)', 1495, 1435, 1, 1, 0, 0, 0, 0, 37.4903245, 126.8256021)
(105, 3, '(주)한미석유구로그린주유소', '서울', '구로구', '서울 구로구 구로중앙로 76 (구로동)', 1499, 1439, 1, 1, 0, 1, 0, 0, 37.4963064, 126.8884444)
(106, 4, '극동유화(주) 항동주유소', '서울', '구로구', '서울 구로구 서해안로 2154 (항동)', 1519, 1449, 1, 1, 0, 0, 0, 0, 37.4834391, 126.8278279)
(107, 1, '구인주유소', '서울', '구로구', '서울 구로구 경인로 558 (구로동)', 1539, 1479, 0, 1, 0, 1, 1, 0, 37.5042779, 126.8860944)
(108, 1, 'SK구로주유소', '서울', '구로구', '서울 구로구 구일로 94 (구로동)', 1539, 1479, 0, 1, 0, 0, 0, 0, 37.4936018, 126.872189)
(109, 2, '신성주유소', '서울', '구로구', '서울 구로구 구로동로 187 (구로제2동)', 1539, 1479, 1, 1, 0, 0, 0, 0, 37.4951588, 126.8823886)
(110, 3, '대성산업(주)디큐브주유소', '서울', '구로구', '서울 구로구 경인로 650 (신도림동)', 1555, 1469, 0, 0, 0, 0, 0, 1, 37.5078855, 126.8870874)
(111, 2, 'HD현대오일뱅크㈜직영 구로셀프주유소', '서울', '구로구', '서울 구로구 시흥대로 531', 1574, 1474, 1, 1, 0, 1, 0, 1, 37.4810027, 126.8992662)
(112, 1, 'SK에너지(주)직영 개봉동주유소', '서울', '구로구', '서울 구로구 경인로 290 (개봉동)', 1577, 1514, 0, 1, 0, 0, 0, 0, 37.4863899, 126.8567675)
(113, 2, 'HD현대오일뱅크㈜직영 신구로주유소', '서울', '구로구', '서울 구로구 가마산로 293 (구로동)', 1584, 1513, 0, 1, 0, 0, 0, 0, 37.4975223, 126.8924841)
(114, 2, '대원셀프주유소', '서울', '구로구', '서울 구로구 개봉로 7', 1597, 1497, 1, 1, 0, 0, 0, 0, 37.4861643, 126.8561585)
(115, 2, '개봉주유소', '서울', '구로구', '서울 구로구 고척로 115 (개봉동)', 1597, 1497, 1, 1, 0, 0, 0, 0, 37.5019372, 126.8468175)
(116, 4, '동아주유소', '서울', '구로구', '서울 구로구 도림로 91 (구로동)', 1798, 1598, 0, 0, 0, 0, 1, 0, 37.4908509, 126.8931878)
(117, 2, 'JHC에너지', '서울', '구로구', '서울 구로구 시흥대로 539', 1853, 1763, 0, 0, 0, 1, 0, 0, 37.4815266, 126.8998375)
(118, 1, '(주)화동유업 화동주유소', '서울', '금천구', '서울 금천구 시흥대로 484', 1532, 1454, 1, 1, 0, 0, 0, 0, 37.4767974, 126.8991596)
(119, 4, '구광주유소', '서울', '금천구', '서울 금천구 서부샛길 674 (가산동)', 1535, 1445, 0, 1, 0, 0, 0, 0, 37.4820373, 126.8751711)
(120, 2, 'HD현대오일뱅크㈜직영 금천현대셀프주유소', '서울', '금천구', '서울 금천구 독산로 147 (시흥동)', 1549, 1459, 1, 1, 0, 0, 0, 0, 37.460506, 126.9045162)
(121, 3, '대득에너지(금천셀프주유소)', '서울', '금천구', '서울 금천구  시흥대로 81 (시흥동)', 1575, 1475, 1, 1, 0, 0, 1, 1, 37.4412805, 126.9029246)
(122, 4, '백산주유소', '서울', '금천구', '서울특별시 금천구  시흥대로 174 (시흥동)', 1575, 1475, 1, 1, 0, 1, 0, 0, 37.4496856, 126.9029496)
(123, 2, '현대오일뱅크㈜직영 금천제일주유소', '서울', '금천구', '서울 금천구 남부순환로 1410 (독산동)', 1579, 1479, 0, 1, 0, 0, 0, 0, 37.4802077, 126.9074805)
(124, 1, 'SK에너지(주) 이가주유소', '서울', '금천구', '서울 금천구 시흥대로 441', 1595, 1495, 0, 1, 0, 1, 0, 0, 37.4730289, 126.8979341)
(125, 3, '지에스칼텍스(주)일신주유소', '서울', '금천구', '서울 금천구 시흥대로 118', 1625, 1525, 1, 1, 0, 0, 0, 0, 37.4444739, 126.9042657)
(126, 2, '화랑대주유소', '서울', '노원구', '서울 노원구 화랑로 483', 1535, 1465, 1, 1, 0, 0, 0, 0, 37.6195772, 127.0806305)
(127, 3, '이엠석유(주)배꽃나라주유소', '서울', '노원구', '서울 노원구 화랑로 466 (공릉1동)', 1535, 1465, 1, 1, 0, 1, 0, 0, 37.6238137, 127.0735097)
(128, 2, '(주)정건에너지직영', '서울', '노원구', '서울 노원구 노원로17길 29 (하계동)', 1535, 1465, 1, 1, 0, 0, 0, 0, 37.642188, 127.0703943)
(129, 4, '태릉솔밭주유소', '서울', '노원구', '서울 노원구 노원로 49 (공릉동)', 1545, 1475, 1, 1, 0, 0, 0, 1, 37.6259652, 127.0855897)
(130, 1, '삼육주유소', '서울', '노원구', '서울 노원구 화랑로 822 (공릉동)', 1545, 1475, 1, 1, 0, 0, 0, 0, 37.6386379, 127.1090597)
(131, 3, '월계주유소', '서울', '노원구', '서울 노원구 월계로 252 (월계동)', 1545, 1465, 1, 1, 0, 1, 0, 0, 37.6247784, 127.0507659)
(132, 4, '한신주유소', '서울', '노원구', '서울 노원구 동일로 1089 (공릉동)', 1550, 1490, 1, 1, 0, 0, 0, 0, 37.6304722, 127.0909904)
(133, 4, '남선석유(주)구도일주유소 불암', '서울', '노원구', '서울 노원구 한글비석로 268 (중계동)', 1555, 1485, 1, 1, 0, 0, 0, 0, 37.6513513, 127.0772401)
(134, 1, 'SK에너지㈜직영 상계주유소', '서울', '노원구', '서울 노원구 노해로 527 (상계동)', 1579, 1509, 0, 1, 0, 0, 0, 0, 37.6559391, 127.0664063)
(135, 2, '상계동주유소', '서울', '노원구', '서울 노원구 노원로26길 191 (상계동)', 1595, 1525, 0, 0, 0, 1, 0, 0, 37.6583938, 127.0711375)
(136, 3, '성북역주유소', '서울', '노원구', '서울 노원구 광운로 95 (월계동)', 1595, 1555, 0, 1, 0, 0, 0, 0, 37.625771, 127.0599365)
(137, 4, '신성주유소', '서울', '노원구', '서울 노원구 월계로 328 (월계동)', 1598, 1558, 1, 1, 0, 0, 0, 1, 37.6287786, 127.0573351)
(138, 3, '하계삼호주유소', '서울', '노원구', '서울 노원구 공릉로 294 (하계동)', 1745, 1635, 0, 0, 0, 1, 0, 0, 37.6336171, 127.0722855)
(139, 2, '이케이에너지 주식회사', '서울', '도봉구', '서울 도봉구 도봉로 941 (도봉동)', 1490, 1415, 1, 1, 0, 0, 0, 0, 37.6884305, 127.0453374)
(140, 3, '지에스칼텍스㈜ 방학동주유소', '서울', '도봉구', '서울 도봉구 방학로 186', 1510, 1444, 1, 1, 0, 0, 0, 0, 37.6624108, 127.0314758)
(141, 2, '(주)자연에너지 햇살주유소', '서울', '도봉구', '서울 도봉구 방학로 142 (방학동)', 1510, 1434, 1, 1, 0, 0, 0, 0, 37.6630015, 127.0363325)
(142, 4, '(주)헨지스에너지 구도일주유소 도봉', '서울', '도봉구', '서울 도봉구 도봉로 706 (방학동)', 1510, 1434, 1, 1, 0, 1, 0, 0, 37.6668687, 127.0435303)
(143, 3, '지에스칼텍스㈜ 도봉주유소', '서울', '도봉구', '서울 도봉구 도봉로 895 (도봉동)', 1510, 1434, 1, 1, 1, 1, 0, 1, 37.6843915, 127.0456569)
(144, 4, '한이에너지(주) 쌍문주유소', '서울', '도봉구', '서울 도봉구 도봉로 547 (쌍문동)', 1510, 1434, 1, 1, 0, 1, 0, 1, 37.6533557, 127.0271003)
(145, 2, '(주)쌍문셀프주유소', '서울', '도봉구', '서울 도봉구 노해로 161 (쌍문동)', 1520, 1444, 1, 1, 0, 1, 0, 0, 37.649024, 127.02688)
(146, 4, '극동유화(주) 대안주유소', '서울', '도봉구', '서울 도봉구 마들로 574 (창동)', 1525, 1445, 1, 1, 0, 1, 0, 0, 37.6615155, 127.0475247)
(147, 1, '삼미북부셀프주유소', '서울', '도봉구', '서울 도봉구 도봉로 437 (쌍문동)', 1540, 1464, 1, 1, 0, 0, 0, 1, 37.6498293, 127.0200197)
(148, 2, '노원교주유소', '서울', '도봉구', '서울 도봉구 마들로 776 (도봉동)', 1545, 1473, 1, 1, 0, 0, 0, 0, 37.678983, 127.0497224)
(149, 1, '동일석유(주) 창동주유소', '서울', '도봉구', '서울 도봉구  도봉로 434 (창동)', 1545, 1465, 1, 1, 0, 1, 0, 0, 37.6446074, 127.0327486)
(150, 3, '대성산업(주)신창주유소', '서울', '도봉구', '서울 도봉구 덕릉로 267 (창동)', 1555, 1475, 1, 1, 0, 0, 0, 1, 37.6413354, 127.040236)
(151, 4, '오복주유소', '서울', '도봉구', '서울 도봉구 방학로 43', 1625, 1585, 1, 1, 0, 0, 0, 1, 37.662341, 127.0474542)
(152, 2, 'HD현대오일뱅크㈜직영 영신주유소', '서울', '도봉구', '서울 도봉구 방학로 151', 1657, 1577, 0, 1, 0, 0, 0, 0, 37.6623796, 127.0354481)
(153, 1, '동서울고속주유소', '서울', '동대문구', '서울 동대문구 한천로 414', 1517, 1427, 1, 0, 0, 0, 0, 1, 37.5975419, 127.0680331)
(154, 2, '재정제2주유소', '서울', '동대문구', '서울 동대문구 사가정로 90 (전농동)', 1539, 1455, 1, 1, 0, 0, 0, 0, 37.5758698, 127.0556493)
(155, 1, '풍한주유소', '서울', '동대문구', '서울 동대문구 안암로 168', 1545, 1455, 0, 1, 0, 0, 0, 1, 37.5892531, 127.0360122)
(156, 2, '재정주유소', '서울', '동대문구', '서울 동대문구 전농로 121 (전농동)', 1545, 1465, 1, 1, 0, 0, 0, 0, 37.5757038, 127.0574394)
(157, 4, '(주)경동주유소', '서울', '동대문구', '서울 동대문구 이문로 191 (이문동)', 1555, 1465, 1, 1, 0, 0, 0, 0, 37.603596, 127.0617855)
(158, 3, '대성산업㈜청량리주유소', '서울', '동대문구', '서울 동대문구 왕산로 289 (청량리동)', 1558, 1468, 1, 1, 1, 0, 0, 1, 37.5814177, 127.0450724)
(159, 3, '대성산업(주)동마장주유소', '서울', '동대문구', '서울 동대문구 고산자로 405 (용두동)', 1558, 1475, 1, 1, 0, 1, 0, 1, 37.5756916, 127.0377503)
(160, 3, '(주)파랑에너지', '서울', '동대문구', '서울 동대문구 망우로 126', 1559, 1475, 1, 1, 0, 0, 0, 0, 37.5912312, 127.067054)
(161, 4, '홍능주유소', '서울', '동대문구', '서울 동대문구 홍릉로 87 (청량리동)', 1575, 1515, 0, 1, 0, 0, 0, 0, 37.587938, 127.0426612)
(162, 1, '삼영주유소', '서울', '동대문구', '서울 동대문구 답십리로 258 (장안동)', 1577, 1487, 0, 1, 0, 0, 0, 0, 37.5723064, 127.0688224)
(163, 2, 'HD현대오일뱅크㈜직영 스피드주유소', '서울', '동대문구', '서울 동대문구 천호대로 453 (장안동)', 1589, 1509, 0, 1, 0, 0, 0, 1, 37.5632059, 127.0696316)
(164, 1, '(주)안국에너지 삼원셀프주유소', '서울', '동대문구', '서울 동대문구 망우로 90 (휘경동)', 1598, 1518, 1, 1, 0, 0, 0, 0, 37.5901827, 127.0632663)
(165, 1, '삼미상사(주)장안킹셀프주유소', '서울', '동대문구', '서울 동대문구  한천로 100 (장안동)', 1637, 1557, 1, 1, 0, 0, 0, 0, 37.5790352, 127.0696452)
(166, 2, '배봉로주유소', '서울', '동대문구', '서울 동대문구 서울시립대로 108', 1655, 1560, 1, 1, 0, 0, 0, 0, 37.5800151, 127.0510496)
(167, 2, 'HD현대오일뱅크㈜직영 신대방셀프주유소', '서울', '동작구', '서울 동작구 시흥대로 616 (신대방동)', 1579, 1484, 1, 1, 0, 1, 0, 1, 37.4871204, 126.9056444)
(168, 2, '창원이엔지주유소', '서울', '동작구', '서울 동작구 사당로 59 (상도동)', 1585, 1485, 1, 1, 0, 0, 0, 0, 37.4948674, 126.9613387)
(169, 4, '매일주유소', '서울', '동작구', '서울 동작구 상도로 139 (상도동)', 1599, 1579, 1, 1, 0, 0, 0, 0, 37.5027348, 126.9350838)
(170, 2, 'HD현대오일뱅크㈜직영 사당셀프주유소', '서울', '동작구', '서울 동작구 동작대로 73 (사당동)', 1604, 1559, 1, 1, 0, 0, 0, 1, 37.4831082, 126.9815397)
(171, 3, '지에스칼텍스㈜직영 남성주유소', '서울', '동작구', '서울 동작구 동작대로 135 (사당동)', 1604, 1564, 1, 0, 0, 0, 0, 1, 37.4886815, 126.9819661)
(172, 2, 'HD현대오일뱅크㈜직영 흑석동셀프주유소', '서울', '동작구', '서울 동작구 현충로 101 (흑석동)', 1614, 1569, 1, 1, 0, 0, 0, 1, 37.5080132, 126.9652693)
(173, 2, 'HD현대오일뱅크㈜직영 동작주유소', '서울', '동작구', '서울 동작구 상도로 403 (상도동)', 1624, 1574, 0, 1, 0, 0, 0, 0, 37.4934739, 126.9565221)
(174, 2, '성산대교셀프주유소', '서울', '마포구', '서울 마포구 성산로 144', 1529, 1499, 1, 1, 0, 1, 0, 0, 37.5642985, 126.9093474)

In [98]:
driver.quit()

In [104]:
remote.close()

문제 5.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작성)
- 전체 데이터를 가져오는데, 주유소 브랜드 아이디 대신 브랜드명이 표시되어야 합니다. (정렬 : 주유소 매장 아이디 순)
- 다음의 형식으로 저장되어야 함 (브랜드 이름, 칼럼 명 주의, id : GAS_STORE.id)

제출 5.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

In [105]:
conn = mysql.connector.connect(
    host = 'database-1.cfc20ugqgb4j.ap-northeast-2.rds.amazonaws.com',
    port = 3306,
    user = 'oneday',
    password = '1234',
    database = 'oneday'
)
cursor = conn.cursor(buffered=True)

In [107]:
sql = 'select * from GAS_STATION'

In [108]:
cursor.execute(sql)

result = cursor.fetchall()
for row in result:
    print(row)

(1, 1, '(주)보성 세곡주유소', '서울', '강남구', '서울 강남구  헌릉로 731 (세곡동)', 1559, 1469, 1, 1, 0, 0, 0, 0, Decimal('37.46715650000000'), Decimal('127.11870810000000'))
(2, 2, 'HD현대오일뱅크㈜직영 산성셀프주유소', '서울', '강남구', '서울 강남구 헌릉로 730', 1574, 1494, 1, 1, 0, 0, 0, 0, Decimal('37.46656750000000'), Decimal('127.11908030000000'))
(3, 1, '자곡셀프주유소', '서울', '강남구', '서울 강남구 밤고개로 120 (자곡동)', 1598, 1559, 1, 1, 0, 0, 0, 0, Decimal('37.48340020000000'), Decimal('127.10404580000000'))
(4, 4, '극동유화㈜ 개나리주유소', '서울', '강남구', '서울 강남구 언주로 423 (역삼동)', 1615, 1535, 1, 1, 0, 1, 0, 1, Decimal('37.50007760000000'), Decimal('127.03854190000000'))
(5, 3, '방죽주유소', '서울', '강남구', '서울 강남구 밤고개로 215 (율현동)', 1617, 1539, 1, 1, 0, 0, 0, 0, Decimal('37.47499260000000'), Decimal('127.10688660000000'))
(6, 2, 'HD현대오일뱅크㈜직영 도곡셀프주유소', '서울', '강남구', '서울 강남구  남부순환로 2718 (도곡2동)', 1619, 1539, 1, 1, 0, 1, 0, 0, Decimal('37.48546230000000'), Decimal('127.04321810000000'))
(7, 1, '오일프러스 셀프', '서울', '강남구', '서울 강남구 남부순환로 2651 (도곡동)', 1625, 1545, 1, 1, 0, 1, 0, 1, Decimal('37.48583900000000'), Decimal('127.03967210000000'))
(8, 2, '삼성동주유소', '서울', '강남구', '서울 강남구 테헤란로 619 (삼성동)', 1635, 1565, 1, 1, 0, 0, 0, 0, Decimal('37.50985760000000'), Decimal('127.06511010000000'))
(9, 2, 'HD현대오일뱅크㈜직영 유진주유소', '서울', '강남구', '서울 강남구 논현로 152 (도곡동)', 1639, 1564, 0, 1, 0, 1, 0, 0, Decimal('37.48743160000000'), Decimal('127.03999760000000'))
(10, 1, '(주)중앙에너비스 수서지점', '서울', '강남구', '서울 강남구 광평로 202 (수서동)', 1657, 1597, 1, 1, 0, 0, 0, 0, Decimal('37.48410530000000'), Decimal('127.09504010000000'))
(11, 1, '대교셀프주유소', '서울', '강남구', '서울 강남구 강남대로 640 (신사동)', 1680, 1650, 1, 0, 0, 0, 0, 1, Decimal('37.52812920000000'), Decimal('127.03555370000000'))
(12, 1, 'SK서광주유소', '서울', '강남구', '서울 강남구 역삼로 142', 1685, 1615, 1, 1, 0, 1, 0, 1, Decimal('37.49434240000000'), Decimal('127.03509150000000'))
(13, 4, '(주)선진도곡주유소', '서울', '강남구', '서울 강남구 도곡로 162 (도곡동)', 1698, 1615, 0, 1, 0, 1, 0, 0, Decimal('37.48782540000000'), Decimal('127.04668760000000'))
(14, 1, 'SK에너지㈜ 진달래주유소', '서울', '강남구', '서울 강남구 도곡로 208', 1699, 1615, 0, 1, 0, 0, 0, 0, Decimal('37.49229500000000'), Decimal('127.04185980000000'))
(15, 3, '지에스칼텍스㈜에너지플러스허브GS타워', '서울', '강남구', '서울 강남구 논현로 516 (역삼동)', 1709, 1679, 1, 0, 0, 1, 0, 1, Decimal('37.50270830000000'), Decimal('127.03639560000000'))
(16, 1, '(유)동하석유 힐탑셀프주유소', '서울', '강남구', '서울 강남구 논현로 640', 1737, 1697, 1, 1, 0, 0, 0, 1, Decimal('37.51068870000000'), Decimal('127.03256890000000'))
(17, 1, '대동석유 압구정주유소', '서울', '강남구', '서울 강남구 언주로 842 (신사동)', 1747, 1697, 1, 1, 0, 0, 0, 1, Decimal('37.52534310000000'), Decimal('127.03382420000000'))
(18, 3, '대양산업(주) 개포주유소', '서울', '강남구', '서울 강남구 양재대로 339', 1788, 0, 1, 1, 0, 0, 0, 0, Decimal('37.47224090000000'), Decimal('127.05151340000000'))
(19, 3, '지에스칼텍스㈜ 삼성로주유소', '서울', '강남구', '서울 강남구 삼성로 563 (삼성동)', 1864, 1839, 1, 1, 0, 0, 0, 1, Decimal('37.51397500000000'), Decimal('127.05612740000000'))
(20, 2, 'HD현대오일뱅크㈜직영 신사현대주유소', '서울', '강남구', '서울 강남구 도산대로 163 (신사동)', 1878, 1834, 0, 1, 0, 0, 0, 0, Decimal('37.51952050000000'), Decimal('127.02631710000000'))
(21, 3, '지에스칼텍스㈜ 은마주유소', '서울', '강남구', '서울 강남구 영동대로 235', 1884, 1792, 0, 1, 0, 1, 0, 1, Decimal('37.50007210000000'), Decimal('127.06728480000000'))
(22, 3, '대성석유(주)동호주유소', '서울', '강남구', '서울 강남구 봉은사로113길 51', 1929, 1822, 0, 1, 0, 0, 0, 0, Decimal('37.51848600000000'), Decimal('127.06466550000000'))
(23, 3, '지에스칼텍스(주)학여울주유소', '서울', '강남구', '서울 강남구 남부순환로 3170 (일원2동)', 2015, 1940, 0, 1, 0, 0, 0, 0, Decimal('37.49467620000000'), Decimal('127.07783050000000'))
(24, 2, 'HD현대오일뱅크㈜직영 한양주유소', '서울', '강남구', '서울 강남구 압구정로 302 (신사동)', 2083, 2026, 0, 1, 0, 0, 0, 0, Decimal('37.52886810000000'), Decimal('127.03410460000000'))
(25, 4, '명품주유소', '서울', '강남구', '서울 강남구 도곡로 249 (역삼동)', 2128, 2037, 1, 1, 0, 0, 0, 1, Decimal('37.49427040000000'), Decimal('127.04550930000000'))
(26, 3, '(주)소모 쎈트럴주유소', '서울', '강남구', '서울 강남구 삼성로 335', 2147, 2072, 0, 1, 0, 0, 0, 0, Decimal('37.50142090000000'), Decimal('127.05914080000000'))
(27, 1, '대청주유소', '서울', '강남구', '서울 강남구 개포로 654 (일원동)', 2195, 2086, 0, 1, 0, 0, 0, 0, Decimal('37.49247370000000'), Decimal('127.08567900000000'))
(28, 2, '㈜새서울석유 새서울주유소', '서울', '강남구', '서울 강남구 압구정로 154', 2198, 2098, 0, 1, 0, 0, 0, 1, Decimal('37.52583500000000'), Decimal('127.02654220000000'))
(29, 1, 'SK논현주유소', '서울', '강남구', '서울 강남구 논현로 747 (논현동)', 2395, 2295, 0, 1, 0, 1, 0, 1, Decimal('37.51863680000000'), Decimal('127.02823800000000'))
(30, 2, '(주)제이제이네트웍스 제이제이주유소', '서울', '강남구', '서울 강남구 언주로 716', 2490, 2380, 0, 1, 0, 0, 0, 1, Decimal('37.51764720000000'), Decimal('127.03573490000000'))
(31, 3, '(주)만정에너지 삼보주유소', '서울', '강남구', '서울 강남구 봉은사로 433 (삼성동)', 2598, 2560, 0, 1, 0, 0, 0, 0, Decimal('37.51152070000000'), Decimal('127.04717160000000'))
(32, 2, '재건에너지 재정제2주유소 고속셀프지점', '서울', '강동구', '서울특별시 강동구  천호대로 1246 (둔촌제2동)', 1559, 1469, 1, 1, 0, 0, 0, 0, Decimal('37.53651330000000'), Decimal('127.14935880000000'))
(33, 3, '대성석유(주)길동주유소', '서울', '강동구', '서울 강동구 천호대로 1168', 1636, 1558, 0, 1, 0, 0, 0, 0, Decimal('37.53342290000000'), Decimal('127.14117250000000'))
(34, 3, '(주)소모 신월주유소', '서울', '강동구', '서울 강동구 양재대로 1323 (성내동)', 1656, 1578, 1, 1, 0, 0, 0, 0, Decimal('37.53049330000000'), Decimal('127.12899200000000'))
(35, 3, '(주)삼표에너지 고덕주유소', '서울', '강동구', '서울 강동구 고덕로 39 (암사동)', 1665, 1585, 1, 1, 0, 0, 1, 0, Decimal('37.55504900000000'), Decimal('127.12979290000000'))
(36, 1, '방아다리주유소', '서울', '강동구', '서울 강동구 동남로 811 (명일동)', 1665, 1575, 1, 1, 0, 0, 0, 0, Decimal('37.54904450000000'), Decimal('127.15082290000000'))
(37, 1, 'sk해뜨는주유소', '서울', '강동구', '서울 강동구  상일로 132 (강일동)', 1699, 1609, 1, 1, 0, 1, 0, 0, Decimal('37.55450850000000'), Decimal('127.17241540000000'))
(38, 3, '(주)소모 성내주유소', '서울', '강동구', '서울 강동구 올림픽로 578 (성내동)', 1708, 1608, 1, 1, 0, 1, 0, 0, Decimal('37.53137820000000'), Decimal('127.12732860000000'))
(39, 4, '(주)퍼스트오일 코알라주유소', '서울', '강동구', '서울특별시 강동구  올림픽로 556 (성내동)', 1710, 1610, 1, 1, 0, 0, 0, 0, Decimal('37.52938080000000'), Decimal('127.12244080000000'))
(40, 3, '지에스칼텍스㈜ 동서울주유소', '서울', '강동구', '서울 강동구 천호대로 1456 (상일동)', 1711, 1639, 1, 1, 0, 0, 0, 0, Decimal('37.55110280000000'), Decimal('127.16964010000000'))
(41, 1, '주)지유에너지직영 오렌지주유소', '서울', '강동구', '서울 강동구 성안로 102 (성내동)', 1754, 1654, 0, 1, 0, 1, 0, 0, Decimal('37.53231400000000'), Decimal('127.13317810000000'))
(42, 2, '천호현대주유소', '서울', '강동구', '서울 강동구 천중로 67 (천호동)', 1843, 1743, 0, 1, 0, 1, 0, 0, Decimal('37.54513310000000'), Decimal('127.12947300000000'))
(43, 4, '광성주유소', '서울', '강동구', '서울 강동구 올림픽로 673 (천호동)', 1968, 1858, 0, 1, 0, 1, 0, 1, Decimal('37.54161170000000'), Decimal('127.12417310000000'))
(44, 1, '북서울고속주유소', '서울', '강북구', '서울 강북구 삼양로 410 (수유동)', 1510, 1434, 1, 0, 0, 0, 0, 1, Decimal('37.64014480000000'), Decimal('127.01720500000000'))
(45, 3, '수유동주유소', '서울', '강북구', '서울 강북구 도봉로 395 (수유동)', 1510, 1434, 1, 1, 0, 0, 0, 1, Decimal('37.64215560000000'), Decimal('127.02958620000000'))
(46, 1, 'SK에너지(주) 매일주유소', '서울', '강북구', '서울 강북구 삼양로 217 (미아동)', 1535, 1455, 1, 1, 0, 0, 1, 0, Decimal('37.62279770000000'), Decimal('127.01913560000000'))
(47, 4, '씨앤에스유통㈜ 미아셀프주유소', '서울', '강북구', '서울 강북구 도봉로 200 (미아동)', 1545, 1455, 1, 1, 0, 0, 0, 0, Decimal('37.62652920000000'), Decimal('127.02650020000000'))
(48, 1, '에덴주유소', '서울', '강북구', '서울 강북구 월계로 195 (번동)', 1545, 1465, 1, 1, 0, 1, 0, 0, Decimal('37.62169580000000'), Decimal('127.04553440000000'))
(49, 4, '덕릉로주유소', '서울', '강북구', '서울 강북구 덕릉로 158 (번동)', 1545, 1455, 1, 1, 0, 0, 0, 0, Decimal('37.63497560000000'), Decimal('127.03131820000000'))
(50, 3, '㈜지에스이앤알 미아주유소', '서울', '강북구', '서울 강북구 도봉로 122 (미아동)', 1555, 1459, 1, 1, 0, 0, 0, 0, Decimal('37.61999640000000'), Decimal('127.02903040000000'))
(51, 3, '대성석유(주)신광주유소', '서울', '강북구', '서울 강북구 삼양로 484', 1559, 1479, 0, 1, 0, 1, 0, 0, Decimal('37.64640880000000'), Decimal('127.01532850000000'))
(52, 2, 'HD현대오일뱅크㈜직영 번동셀프주유소', '서울', '강북구', '서울 강북구 한천로 963 (번동)', 1577, 1497, 1, 1, 0, 1, 0, 1, Decimal('37.63558720000000'), Decimal('127.03304930000000'))
(53, 1, '세원주유소', '서울', '강북구', '서울 강북구 한천로 918 (번동)', 1578, 1498, 1, 1, 0, 0, 0, 0, Decimal('37.63425960000000'), Decimal('127.03773200000000'))
(54, 1, '강서오곡셀프주유소', '서울', '강서구', '서울 강서구 벌말로 254 (오곡동)', 1493, 1409, 1, 1, 0, 0, 0, 1, Decimal('37.55396220000000'), Decimal('126.76842750000000'))
(55, 5, '목화주유소', '서울', '강서구', '서울 강서구 국회대로 251 (화곡동)', 1495, 1424, 1, 1, 0, 0, 0, 0, Decimal('37.53004030000000'), Decimal('126.86298250000000'))
(56, 2, '행촌에너지 공항주유소', '서울', '강서구', '서울 강서구 개화동로 420 (개화동)', 1495, 1443, 1, 1, 0, 1, 1, 1, Decimal('37.57461100000000'), Decimal('126.80230290000000'))
(57, 4, '스카이주유소', '서울', '강서구', '서울 강서구 개화동로 457 (방화동)', 1495, 1443, 1, 1, 0, 0, 1, 1, Decimal('37.57148580000000'), Decimal('126.80438060000000'))
(58, 2, '이케이에너지(주) 강서주유소', '서울', '강서구', '서울 강서구 화곡로 273 (화곡동)', 1504, 1422, 1, 1, 0, 1, 0, 0, Decimal('37.54916300000000'), Decimal('126.84699640000000'))
(59, 5, '화곡역주유소', '서울', '강서구', '서울 강서구 강서로 154 (화곡동)', 1504, 1422, 1, 0, 0, 0, 0, 1, Decimal('37.54071860000000'), Decimal('126.84153030000000'))
(60, 3, '지에스칼텍스㈜ 경인고속주유소', '서울', '강서구', '서울 강서구 국회대로 225 (화곡동)', 1505, 1434, 1, 1, 1, 1, 0, 1, Decimal('37.52962090000000'), Decimal('126.85979700000000'))
(61, 5, '뉴신정주유소', '서울', '강서구', '서울 강서구 곰달래로 207 (화곡동)', 1506, 1424, 0, 0, 0, 1, 0, 0, Decimal('37.53157960000000'), Decimal('126.85605240000000'))
(62, 1, 'KH에너지(주)직영 KH외발산주유소', '서울', '강서구', '서울 강서구 방화대로 30', 1550, 1480, 1, 1, 1, 1, 1, 0, Decimal('37.54342080000000'), Decimal('126.81686300000000'))
(63, 2, '현대오일뱅크 등촌주유소', '서울', '강서구', '서울 강서구 등촌로 189 (등촌동)', 1576, 1496, 0, 1, 0, 0, 0, 0, Decimal('37.54680800000000'), Decimal('126.86255450000000'))
(64, 1, '개화주유소', '서울', '강서구', '서울 강서구 양천로 57', 1577, 1517, 1, 1, 0, 0, 0, 0, Decimal('37.57350140000000'), Decimal('126.81009430000000'))
(65, 2, 'HD현대오일뱅크㈜직영 양화교셀프주유소', '서울', '강서구', '서울 강서구 공항대로 653', 1579, 1524, 1, 1, 0, 0, 0, 0, Decimal('37.54733680000000'), Decimal('126.87747640000000'))
(66, 4, '하이웨이주유소', '서울', '강서구', '서울특별시 강서구 공항대로 432(화곡동)', 1579, 1514, 1, 1, 0, 0, 1, 1, Decimal('37.55466770000000'), Decimal('126.85480530000000'))
(67, 4, '(주)한진 김포공항주유소', '서울', '강서구', '서울 강서구 하늘길 259', 1590, 1530, 1, 1, 0, 0, 0, 0, Decimal('37.55077630000000'), Decimal('126.81555490000000'))
(68, 4, '신화곡주유소', '서울', '강서구', '서울 강서구 국회대로 71', 1595, 1495, 1, 1, 0, 0, 0, 0, Decimal('37.52725790000000'), Decimal('126.84288960000000'))
(69, 1, '화곡현대주유소', '서울', '강서구', '서울 강서구 강서로 151 (화곡동)', 1596, 1566, 1, 1, 0, 0, 0, 1, Decimal('37.54026140000000'), Decimal('126.84119830000000'))
(70, 3, '대성석유(주) 관문주유소', '서울', '강서구', '서울 강서구 공항대로 314', 1598, 1578, 0, 1, 0, 1, 0, 0, Decimal('37.55772320000000'), Decimal('126.84252430000000'))
(71, 3, '강서열린주유소', '서울', '강서구', '서울 강서구 등촌로 213 (등촌동)', 1598, 1528, 0, 1, 0, 0, 0, 0, Decimal('37.54871200000000'), Decimal('126.86306280000000'))
(72, 2, 'HD현대오일뱅크㈜직영 가양주유소', '서울', '강서구', '서울 강서구  양천로 391 (가양동)', 1599, 1559, 0, 1, 0, 0, 0, 0, Decimal('37.56788020000000'), Decimal('126.85107870000000'))
(73, 3, '대성석유(주)방화대성주유소', '서울', '강서구', '서울 강서구 양천로 176', 1616, 1578, 1, 1, 0, 0, 1, 0, Decimal('37.57288150000000'), Decimal('126.82348210000000'))
(74, 3, '대성주유소', '서울', '강서구', '서울 강서구 강서로 472', 1638, 1598, 0, 1, 0, 1, 0, 0, Decimal('37.56750280000000'), Decimal('126.84141860000000'))
(75, 1, 'SK KH에너지 가양주유소', '서울', '강서구', '서울 강서구 강서로 498 (가양동)', 1638, 1598, 0, 1, 0, 1, 1, 1, Decimal('37.56978230000000'), Decimal('126.84190220000000'))
(76, 1, '세원제1주유소', '서울', '강서구', '서울 강서구 양천로 311 (가양동)', 1648, 1598, 1, 1, 0, 1, 0, 0, Decimal('37.56788020000000'), Decimal('126.85107870000000'))
(77, 3, '박물관주유소', '서울', '강서구', '서울 강서구 양천로53길 97 (가양동)', 1678, 1638, 0, 1, 0, 1, 1, 0, Decimal('37.56578490000000'), Decimal('126.84512160000000'))
(78, 1, '코리나(주)청룡주유소', '서울', '강서구', '서울 강서구 양천로 576', 1698, 1638, 0, 1, 0, 0, 0, 0, Decimal('37.55673250000000'), Decimal('126.86276500000000'))
(79, 4, '참솔에너지', '서울', '강서구', '서울 강서구 벌말로 281 (오곡동)', 1798, 1698, 1, 1, 0, 0, 0, 0, Decimal('37.55625190000000'), Decimal('126.76844910000000'))
(80, 1, '염창동주유소', '서울', '강서구', '서울 강서구 양천로 720 (염창동)', 1935, 1860, 0, 1, 0, 0, 0, 0, Decimal('37.54911130000000'), Decimal('126.87579060000000'))
(81, 2, 'HD현대오일뱅크㈜직영 문성골주유소', '서울', '관악구', '서울 관악구 문성로 97 (신림동)', 1559, 1464, 0, 1, 0, 0, 0, 0, Decimal('37.47779410000000'), Decimal('126.91430220000000'))
(82, 5, '(주)연우에너지 신관주유소', '서울', '관악구', '서울 관악구 신림로 290 (신림동)', 1565, 1465, 1, 1, 0, 0, 0, 0, Decimal('37.48041300000000'), Decimal('126.93066650000000'))
(83, 1, '(주)한유에너지행운셀프주유소', '서울', '관악구', '서울 관악구 남부순환로 1883 (봉천동)', 1565, 1465, 1, 1, 0, 0, 0, 0, Decimal('37.47910830000000'), Decimal('126.95916970000000'))
(84, 3, '서일석유(주)락성주유소', '서울', '관악구', '서울 관악구 남부순환로 1920 (봉천동)', 1575, 1475, 1, 1, 0, 1, 0, 1, Decimal('37.47717920000000'), Decimal('126.96238830000000'))
(85, 1, '대양석유(주)직영 보라매주유소', '서울', '관악구', '서울 관악구  보라매로 26 (봉천동)', 1575, 1475, 1, 1, 0, 0, 0, 0, Decimal('37.49168740000000'), Decimal('126.92716030000000'))
(86, 1, 'SK에너지(주) 신봉천', '서울', '관악구', '서울 관악구 남부순환로 1880 (봉천동)', 1585, 1485, 0, 1, 0, 0, 1, 0, Decimal('37.47875720000000'), Decimal('126.95834320000000'))
(87, 1, 'SK에너지(주)직영 대공원주유소', '서울', '관악구', '서울 관악구 과천대로 921 (남현동)', 1585, 1485, 0, 1, 0, 1, 1, 0, Decimal('37.47285560000000'), Decimal('126.98215150000000'))
(88, 4, '유림주유소', '서울', '관악구', '서울 관악구 신림로 176 (신림동)', 1598, 1498, 0, 1, 0, 1, 0, 1, Decimal('37.47372470000000'), Decimal('126.93488000000000'))
(89, 4, '관악시몬주유소', '서울', '관악구', '서울특별시 관악구 남부순환로 1753 (봉천동)', 1695, 1595, 0, 1, 0, 0, 0, 0, Decimal('37.48235850000000'), Decimal('126.94510100000000'))
(90, 3, 'CJ대한통운㈜ 신림주유소', '서울', '관악구', '서울 관악구 남부순환로 1515 (신림동)', 1748, 1668, 0, 1, 0, 0, 0, 0, Decimal('37.48294960000000'), Decimal('126.91895530000000'))
(91, 2, 'HD현대오일뱅크㈜직영 능동주유소', '서울', '광진구', '서울 광진구 천호대로 584 (능동)', 1529, 1445, 1, 1, 0, 1, 0, 1, Decimal('37.55555510000000'), Decimal('127.08245500000000'))
(92, 2, '태양주유소', '서울', '광진구', '서울 광진구 동일로 345 (중곡동)', 1534, 1454, 0, 0, 0, 0, 0, 1, Decimal('37.56354400000000'), Decimal('127.08883040000000'))
(93, 2, '(주)창원CW', '서울', '광진구', '서울 광진구 광나루로 460 (화양동)', 1539, 1455, 1, 1, 0, 0, 0, 0, Decimal('37.54510420000000'), Decimal('127.08049690000000'))
(94, 1, '(주)장수주유소', '서울', '광진구', '서울 광진구 동일로 266 (군자동)', 1547, 1467, 1, 0, 0, 1, 0, 1, Decimal('37.55497210000000'), Decimal('127.07151970000000'))
(95, 2, 'HD현대오일뱅크㈜직영 중원셀프주유소', '서울', '광진구', '서울 광진구 동일로 398 (중곡동)', 1548, 1469, 1, 1, 0, 0, 0, 0, Decimal('37.56354400000000'), Decimal('127.08883040000000'))
(96, 2, 'HD현대오일뱅크㈜직영 중곡현대주유소', '서울', '광진구', '서울 광진구 동일로 435 (중곡동)', 1548, 1469, 1, 1, 0, 0, 0, 0, Decimal('37.56094120000000'), Decimal('127.09574580000000'))
(97, 2, 'HD현대오일뱅크㈜직영 장호셀프주유소', '서울', '광진구', '서울 광진구 자양로 37 (자양동)', 1548, 1475, 1, 1, 0, 1, 0, 0, Decimal('37.53127830000000'), Decimal('127.08583250000000'))
(98, 4, '정해네트웍스(주)일진주유소', '서울', '광진구', '서울 광진구 동일로 413 (중곡동)', 1567, 1487, 1, 1, 0, 0, 0, 1, Decimal('37.56354400000000'), Decimal('127.08883040000000'))
(99, 4, '삼호주유소', '서울', '광진구', '서울 광진구 천호대로 809 (광장동)', 1697, 1597, 1, 1, 0, 0, 0, 1, Decimal('37.54563560000000'), Decimal('127.10373410000000'))
(100, 1, '유니스에너지 자양주유소', '서울', '광진구', '서울 광진구 아차산로 298 (자양동)', 1698, 1598, 0, 1, 0, 0, 0, 1, Decimal('37.53169200000000'), Decimal('127.07451600000000'))
(101, 1, '강평주유소 ㈜강평텔레콤', '서울', '광진구', '서울 광진구 아차산로 616', 1798, 1697, 0, 1, 0, 0, 0, 0, Decimal('37.54761190000000'), Decimal('127.10720510000000'))
(102, 1, '서서울고속주유소', '서울', '구로구', '서울 구로구 경인로 150 (오류동)', 1490, 1415, 1, 1, 0, 0, 0, 1, Decimal('37.49167510000000'), Decimal('126.84284180000000'))
(103, 2, '㈜자연에너지 고척주유소', '서울', '구로구', '서울 구로구 고척로 199 (고척동)', 1490, 1415, 1, 1, 0, 0, 0, 0, Decimal('37.50512730000000'), Decimal('126.85544060000000'))
(104, 4, '씨앤에스유통(주) 구로드림주유소', '서울', '구로구', '서울 구로구 경인로 41 (온수동)', 1495, 1435, 1, 1, 0, 0, 0, 0, Decimal('37.49032450000000'), Decimal('126.82560210000000'))
(105, 3, '(주)한미석유구로그린주유소', '서울', '구로구', '서울 구로구 구로중앙로 76 (구로동)', 1499, 1439, 1, 1, 0, 1, 0, 0, Decimal('37.49630640000000'), Decimal('126.88844440000000'))
(106, 4, '극동유화(주) 항동주유소', '서울', '구로구', '서울 구로구 서해안로 2154 (항동)', 1519, 1449, 1, 1, 0, 0, 0, 0, Decimal('37.48343910000000'), Decimal('126.82782790000000'))
(107, 1, '구인주유소', '서울', '구로구', '서울 구로구 경인로 558 (구로동)', 1539, 1479, 0, 1, 0, 1, 1, 0, Decimal('37.50427790000000'), Decimal('126.88609440000000'))
(108, 1, 'SK구로주유소', '서울', '구로구', '서울 구로구 구일로 94 (구로동)', 1539, 1479, 0, 1, 0, 0, 0, 0, Decimal('37.49360180000000'), Decimal('126.87218900000000'))
(109, 2, '신성주유소', '서울', '구로구', '서울 구로구 구로동로 187 (구로제2동)', 1539, 1479, 1, 1, 0, 0, 0, 0, Decimal('37.49515880000000'), Decimal('126.88238860000000'))
(110, 3, '대성산업(주)디큐브주유소', '서울', '구로구', '서울 구로구 경인로 650 (신도림동)', 1555, 1469, 0, 0, 0, 0, 0, 1, Decimal('37.50788550000000'), Decimal('126.88708740000000'))
(111, 2, 'HD현대오일뱅크㈜직영 구로셀프주유소', '서울', '구로구', '서울 구로구 시흥대로 531', 1574, 1474, 1, 1, 0, 1, 0, 1, Decimal('37.48100270000000'), Decimal('126.89926620000000'))
(112, 1, 'SK에너지(주)직영 개봉동주유소', '서울', '구로구', '서울 구로구 경인로 290 (개봉동)', 1577, 1514, 0, 1, 0, 0, 0, 0, Decimal('37.48638990000000'), Decimal('126.85676750000000'))
(113, 2, 'HD현대오일뱅크㈜직영 신구로주유소', '서울', '구로구', '서울 구로구 가마산로 293 (구로동)', 1584, 1513, 0, 1, 0, 0, 0, 0, Decimal('37.49752230000000'), Decimal('126.89248410000000'))
(114, 2, '대원셀프주유소', '서울', '구로구', '서울 구로구 개봉로 7', 1597, 1497, 1, 1, 0, 0, 0, 0, Decimal('37.48616430000000'), Decimal('126.85615850000000'))
(115, 2, '개봉주유소', '서울', '구로구', '서울 구로구 고척로 115 (개봉동)', 1597, 1497, 1, 1, 0, 0, 0, 0, Decimal('37.50193720000000'), Decimal('126.84681750000000'))
(116, 4, '동아주유소', '서울', '구로구', '서울 구로구 도림로 91 (구로동)', 1798, 1598, 0, 0, 0, 0, 1, 0, Decimal('37.49085090000000'), Decimal('126.89318780000000'))
(117, 2, 'JHC에너지', '서울', '구로구', '서울 구로구 시흥대로 539', 1853, 1763, 0, 0, 0, 1, 0, 0, Decimal('37.48152660000000'), Decimal('126.89983750000000'))
(118, 1, '(주)화동유업 화동주유소', '서울', '금천구', '서울 금천구 시흥대로 484', 1532, 1454, 1, 1, 0, 0, 0, 0, Decimal('37.47679740000000'), Decimal('126.89915960000000'))
(119, 4, '구광주유소', '서울', '금천구', '서울 금천구 서부샛길 674 (가산동)', 1535, 1445, 0, 1, 0, 0, 0, 0, Decimal('37.48203730000000'), Decimal('126.87517110000000'))
(120, 2, 'HD현대오일뱅크㈜직영 금천현대셀프주유소', '서울', '금천구', '서울 금천구 독산로 147 (시흥동)', 1549, 1459, 1, 1, 0, 0, 0, 0, Decimal('37.46050600000000'), Decimal('126.90451620000000'))
(121, 3, '대득에너지(금천셀프주유소)', '서울', '금천구', '서울 금천구  시흥대로 81 (시흥동)', 1575, 1475, 1, 1, 0, 0, 1, 1, Decimal('37.44128050000000'), Decimal('126.90292460000000'))
(122, 4, '백산주유소', '서울', '금천구', '서울특별시 금천구  시흥대로 174 (시흥동)', 1575, 1475, 1, 1, 0, 1, 0, 0, Decimal('37.44968560000000'), Decimal('126.90294960000000'))
(123, 2, '현대오일뱅크㈜직영 금천제일주유소', '서울', '금천구', '서울 금천구 남부순환로 1410 (독산동)', 1579, 1479, 0, 1, 0, 0, 0, 0, Decimal('37.48020770000000'), Decimal('126.90748050000000'))
(124, 1, 'SK에너지(주) 이가주유소', '서울', '금천구', '서울 금천구 시흥대로 441', 1595, 1495, 0, 1, 0, 1, 0, 0, Decimal('37.47302890000000'), Decimal('126.89793410000000'))
(125, 3, '지에스칼텍스(주)일신주유소', '서울', '금천구', '서울 금천구 시흥대로 118', 1625, 1525, 1, 1, 0, 0, 0, 0, Decimal('37.44447390000000'), Decimal('126.90426570000000'))
(126, 2, '화랑대주유소', '서울', '노원구', '서울 노원구 화랑로 483', 1535, 1465, 1, 1, 0, 0, 0, 0, Decimal('37.61957720000000'), Decimal('127.08063050000000'))
(127, 3, '이엠석유(주)배꽃나라주유소', '서울', '노원구', '서울 노원구 화랑로 466 (공릉1동)', 1535, 1465, 1, 1, 0, 1, 0, 0, Decimal('37.62381370000000'), Decimal('127.07350970000000'))
(128, 2, '(주)정건에너지직영', '서울', '노원구', '서울 노원구 노원로17길 29 (하계동)', 1535, 1465, 1, 1, 0, 0, 0, 0, Decimal('37.64218800000000'), Decimal('127.07039430000000'))
(129, 4, '태릉솔밭주유소', '서울', '노원구', '서울 노원구 노원로 49 (공릉동)', 1545, 1475, 1, 1, 0, 0, 0, 1, Decimal('37.62596520000000'), Decimal('127.08558970000000'))
(130, 1, '삼육주유소', '서울', '노원구', '서울 노원구 화랑로 822 (공릉동)', 1545, 1475, 1, 1, 0, 0, 0, 0, Decimal('37.63863790000000'), Decimal('127.10905970000000'))
(131, 3, '월계주유소', '서울', '노원구', '서울 노원구 월계로 252 (월계동)', 1545, 1465, 1, 1, 0, 1, 0, 0, Decimal('37.62477840000000'), Decimal('127.05076590000000'))
(132, 4, '한신주유소', '서울', '노원구', '서울 노원구 동일로 1089 (공릉동)', 1550, 1490, 1, 1, 0, 0, 0, 0, Decimal('37.63047220000000'), Decimal('127.09099040000000'))

In [121]:
df = pd.DataFrame(result)
df.columns = ['id', 'brand', 'name', 'city', 'gu', 'address', 'gasoline', 'diesel', 'self', 'car_wash', 'charging_station', 'car_maintenance' , 'convenience_store',  '24_hour', 'lat', 'lng']
df = df.set_index(keys='id')
df.head()

,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hour,lat,lng
id,,,,,,,,,,,,,,,
1,1,(주)보성 세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1559,1469,1,1,0,0,0,0,37.46715650000000,127.11870810000000
2,2,HD현대오일뱅크㈜직영 산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1574,1494,1,1,0,0,0,0,37.46656750000000,127.11908030000000
3,1,자곡셀프주유소,서울,강남구,서울 강남구 밤고개로 120 (자곡동),1598,1559,1,1,0,0,0,0,37.48340020000000,127.10404580000000
4,4,극동유화㈜ 개나리주유소,서울,강남구,서울 강남구 언주로 423 (역삼동),1615,1535,1,1,0,1,0,1,37.50007760000000,127.03854190000000
5,3,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1617,1539,1,1,0,0,0,0,37.47499260000000,127.10688660000000

In [122]:
df['brand'] = df['brand'].replace(1, 'SK에너지')
df['brand'] = df['brand'].replace(2, '현대오일뱅크')
df['brand'] = df['brand'].replace(3, 'GS칼텍스')
df['brand'] = df['brand'].replace(4, 'S-OIL')
df['brand'] = df['brand'].replace(5, '알뜰주유소')
df['brand'] = df['brand'].replace(6, '자가상표')
df.head()

,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hour,lat,lng
id,,,,,,,,,,,,,,,
1,SK에너지,(주)보성 세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1559,1469,1,1,0,0,0,0,37.46715650000000,127.11870810000000
2,현대오일뱅크,HD현대오일뱅크㈜직영 산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1574,1494,1,1,0,0,0,0,37.46656750000000,127.11908030000000
3,SK에너지,자곡셀프주유소,서울,강남구,서울 강남구 밤고개로 120 (자곡동),1598,1559,1,1,0,0,0,0,37.48340020000000,127.10404580000000
4,S-OIL,극동유화㈜ 개나리주유소,서울,강남구,서울 강남구 언주로 423 (역삼동),1615,1535,1,1,0,1,0,1,37.50007760000000,127.03854190000000
5,GS칼텍스,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1617,1539,1,1,0,0,0,0,37.47499260000000,127.10688660000000

In [123]:
df.to_csv('oil.csv')

문제 6.

위도, 경도 정보를 이용하여 미왕빌딩에서 1킬로 이내에 위치한 주유소 정보를 검색하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 미왕빌딩으로 부터의 거리 (km)

제출 6.
- 쿼리, 결과

https://yusang.tistory.com/48

In [130]:
tmp = get_lat_lng('서울특별시 강남구 강남대로 364')
lat = tmp[0]
lng = tmp[1]
lat, lng

(37.4955525, 127.0292924)

SELECT
    id, brand, name, address,
	 ROUND((6371*acos(cos(radians(37.4955525))*cos(radians(lat))*cos(radians(lng)
    -radians(127.0292924))+sin(radians(37.4955525))*sin(radians(lat)))), 2)
    AS distance

FROM GAS_STATION
	HAVING distance < 1

ORDER BY distance;

``` distance;

+-----+-------+-------------------------------------+-----------------------------------+----------+
| id  | brand | name                                | address                           | distance |
+-----+-------+-------------------------------------+-----------------------------------+----------+
|  12 |     1 | SK서광주유소                        | 서울 강남구 역삼로 142            |     0.53 |
| 210 |     2 | HD현대오일뱅크㈜직영 서초제일주유소 | 서울 서초구 사임당로 116 (서초동) |     0.81 |
|   4 |     4 | 극동유화㈜ 개나리주유소             | 서울 강남구 언주로 423 (역삼동)   |     0.96 |
+-----+-------+-------------------------------------+-----------------------------------+----------+
```

문제 7.

위도, 경도 정보를 이용하여 미왕빌딩에서 셀프주유가 가능하고 24시간이면서 편의점이 있는 가장 가까운 주유소 10개를 휘 발유 가격이 가장 저렴한 순으로 정렬하여 조회하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 휘발유 가격, 부가정보 (셀프, 24시간, 편의점 여부), 미왕빌딩으로 부터의 거리 (km)


제출 7.
- 쿼리, 결과

SELECT
    id, brand, name, address, gasoline, self, 24_hour, convenience_store,
	 ROUND((6371*acos(cos(radians(37.4955525))*cos(radians(lat))*cos(radians(lng)
    -radians(127.0292924))+sin(radians(37.4955525))*sin(radians(lat)))), 2)
    AS distance

FROM GAS_STATION
where self = 1 and 24_hour = 1 and convenience_store = 1
ORDER BY distance, gasoline
limit 10;

```
+-----+-------+-----------------------------------------+-----------------------------------+----------+------+---------+-------------------+----------+
| id  | brand | name                                    | address                           | gasoline | self | 24_hour | convenience_store | distance |
+-----+-------+-----------------------------------------+-----------------------------------+----------+------+---------+-------------------+----------+
| 215 |     1 | 대신석유(주)대우주유소                  | 서울 서초구 양재대로 173 (양재동) |     1649 |    1 |       1 |                 1 |     3.71 |
| 196 |     6 | 만남의광장주유소                        | 서울 서초구 양재대로12길 73-71    |     1514 |    1 |       1 |                 1 |      4.1 |
| 253 |     3 | 지에스칼텍스(주)가든파이브주유소        | 서울 송파구 탄천동로 740          |     1563 |    1 |       1 |                 1 |     5.29 |
| 262 |     1 | 백제고분로주유소                        | 서울 송파구 오금로 143 (방이동)   |     1583 |    1 |       1 |                 1 |     7.95 |
| 190 |     1 | 행촌제2주유소                           | 서울 서대문구 성산로 490 (대신동) |     1595 |    1 |       1 |                 1 |     10.7 |
| 303 |     1 | 행촌주유소                              | 서울 영등포구 도신로 130 (신길동) |     1499 |    1 |       1 |                 1 |    10.95 |
| 312 |     1 | SK에너지(주) 기린주유소                 | 서울 영등포구 선유로 270          |     1599 |    1 |       1 |                 1 |    12.32 |
| 121 |     3 | 대득에너지(금천셀프주유소)              | 서울 금천구  시흥대로 81 (시흥동) |     1575 |    1 |       1 |                 1 |    12.68 |
| 183 |     2 | (주)가재울뉴타운주유소                  | 서울 서대문구 모래내로 205        |     1523 |    1 |       1 |                 1 |    12.79 |
| 288 |     2 | 현대오일뱅크(주)직영 양천현대셀프주유소 | 서울 양천구 안양천로 1179 (목동)  |     1579 |    1 |       1 |                 1 |     14.2 |
+-----+-------+-----------------------------------------+-----------------------------------+----------+------+---------+-------------------+----------+
```

문제 8.

구별로 주유소 브랜드 별 휘발유 평균가격을 조회하여 저렴한 순으로 출력하세요.

- 구 이름, 주유소 브랜드 이름, 휘발유 평균 가격

제출 8.
- 쿼리, 결과

SELECT s.gu, b.name, avg(s.gasoline)
    -> FROM GAS_BRAND as b ,GAS_STATION as s
    -> GROUP BY s.gu, b.name
    -> order by avg(gasoline);

```
+----------+--------------+-----------------+
| gu       | name         | avg(s.gasoline) |
+----------+--------------+-----------------+
| 도봉구   | 자가상표     |       1539.4286 |
| 도봉구   | 알뜰주유소   |       1539.4286 |
| 도봉구   | S-OIL        |       1539.4286 |
| 도봉구   | GS칼텍스     |       1539.4286 |
| 도봉구   | 현대오일뱅크 |       1539.4286 |
| 도봉구   | SK에너지     |       1539.4286 |
| 은평구   | 자가상표     |       1542.3333 |
| 은평구   | 알뜰주유소   |       1542.3333 |
| 은평구   | S-OIL        |       1542.3333 |
| 은평구   | GS칼텍스     |       1542.3333 |
| 은평구   | 현대오일뱅크 |       1542.3333 |
| 은평구   | SK에너지     |       1542.3333 |
| 중랑구   | 자가상표     |       1543.2727 |
| 중랑구   | 알뜰주유소   |       1543.2727 |
| 중랑구   | S-OIL        |       1543.2727 |
| 중랑구   | GS칼텍스     |       1543.2727 |
| 중랑구   | 현대오일뱅크 |       1543.2727 |
| 중랑구   | SK에너지     |       1543.2727 |
| 강북구   | 자가상표     |       1545.9000 |
| 강북구   | 알뜰주유소   |       1545.9000 |
| 강북구   | S-OIL        |       1545.9000 |
| 강북구   | GS칼텍스     |       1545.9000 |
| 강북구   | 현대오일뱅크 |       1545.9000 |
| 강북구   | SK에너지     |       1545.9000 |
| 성북구   | 자가상표     |       1553.6250 |
| 성북구   | 알뜰주유소   |       1553.6250 |
| 성북구   | S-OIL        |       1553.6250 |
| 성북구   | GS칼텍스     |       1553.6250 |
| 성북구   | 현대오일뱅크 |       1553.6250 |
| 성북구   | SK에너지     |       1553.6250 |
| 양천구   | 자가상표     |       1564.8500 |
| 양천구   | 알뜰주유소   |       1564.8500 |
| 양천구   | S-OIL        |       1564.8500 |
| 양천구   | GS칼텍스     |       1564.8500 |
| 양천구   | 현대오일뱅크 |       1564.8500 |
| 양천구   | SK에너지     |       1564.8500 |
| 금천구   | 자가상표     |       1570.6250 |
| 금천구   | 알뜰주유소   |       1570.6250 |
| 금천구   | S-OIL        |       1570.6250 |
| 금천구   | GS칼텍스     |       1570.6250 |
| 금천구   | 현대오일뱅크 |       1570.6250 |
| 금천구   | SK에너지     |       1570.6250 |
| 서대문구 | 자가상표     |       1571.7692 |
| 서대문구 | 알뜰주유소   |       1571.7692 |
| 서대문구 | S-OIL        |       1571.7692 |
| 서대문구 | GS칼텍스     |       1571.7692 |
| 서대문구 | 현대오일뱅크 |       1571.7692 |
| 서대문구 | SK에너지     |       1571.7692 |
| 동대문구 | 자가상표     |       1571.9286 |
| 동대문구 | 알뜰주유소   |       1571.9286 |
| 동대문구 | S-OIL        |       1571.9286 |
| 동대문구 | GS칼텍스     |       1571.9286 |
| 동대문구 | 현대오일뱅크 |       1571.9286 |
| 동대문구 | SK에너지     |       1571.9286 |
| 노원구   | 자가상표     |       1573.6154 |
| 노원구   | 알뜰주유소   |       1573.6154 |
| 노원구   | S-OIL        |       1573.6154 |
| 노원구   | GS칼텍스     |       1573.6154 |
| 노원구   | 현대오일뱅크 |       1573.6154 |
| 노원구   | SK에너지     |       1573.6154 |
| 구로구   | 자가상표     |       1577.8125 |
| 구로구   | 알뜰주유소   |       1577.8125 |
| 구로구   | S-OIL        |       1577.8125 |
| 구로구   | GS칼텍스     |       1577.8125 |
| 구로구   | 현대오일뱅크 |       1577.8125 |
| 구로구   | SK에너지     |       1577.8125 |
| 강서구   | 자가상표     |       1595.6667 |
| 강서구   | 알뜰주유소   |       1595.6667 |
| 강서구   | S-OIL        |       1595.6667 |
| 강서구   | GS칼텍스     |       1595.6667 |
| 강서구   | 현대오일뱅크 |       1595.6667 |
| 강서구   | SK에너지     |       1595.6667 |
| 광진구   | 자가상표     |       1595.7273 |
| 광진구   | 알뜰주유소   |       1595.7273 |
| 광진구   | S-OIL        |       1595.7273 |
| 광진구   | GS칼텍스     |       1595.7273 |
| 광진구   | 현대오일뱅크 |       1595.7273 |
| 광진구   | SK에너지     |       1595.7273 |
| 송파구   | 자가상표     |       1597.3333 |
| 송파구   | 알뜰주유소   |       1597.3333 |
| 송파구   | S-OIL        |       1597.3333 |
| 송파구   | GS칼텍스     |       1597.3333 |
| 송파구   | 현대오일뱅크 |       1597.3333 |
| 송파구   | SK에너지     |       1597.3333 |
| 마포구   | 자가상표     |       1600.0000 |
| 마포구   | 알뜰주유소   |       1600.0000 |
| 마포구   | S-OIL        |       1600.0000 |
| 마포구   | GS칼텍스     |       1600.0000 |
| 마포구   | 현대오일뱅크 |       1600.0000 |
| 마포구   | SK에너지     |       1600.0000 |
| 동작구   | 자가상표     |       1601.2857 |
| 동작구   | 알뜰주유소   |       1601.2857 |
| 동작구   | S-OIL        |       1601.2857 |
| 동작구   | GS칼텍스     |       1601.2857 |
| 동작구   | 현대오일뱅크 |       1601.2857 |
| 동작구   | SK에너지     |       1601.2857 |
| 관악구   | 자가상표     |       1605.0000 |
| 관악구   | 알뜰주유소   |       1605.0000 |
| 관악구   | S-OIL        |       1605.0000 |
| 관악구   | GS칼텍스     |       1605.0000 |
| 관악구   | 현대오일뱅크 |       1605.0000 |
| 관악구   | SK에너지     |       1605.0000 |
| 영등포구 | 자가상표     |       1636.9130 |
| 영등포구 | 알뜰주유소   |       1636.9130 |
| 영등포구 | S-OIL        |       1636.9130 |
| 영등포구 | GS칼텍스     |       1636.9130 |
| 영등포구 | 현대오일뱅크 |       1636.9130 |
| 영등포구 | SK에너지     |       1636.9130 |
| 서초구   | 자가상표     |       1665.1200 |
| 서초구   | 알뜰주유소   |       1665.1200 |
| 서초구   | S-OIL        |       1665.1200 |
| 서초구   | GS칼텍스     |       1665.1200 |
| 서초구   | 현대오일뱅크 |       1665.1200 |
| 서초구   | SK에너지     |       1665.1200 |
| 성동구   | 자가상표     |       1714.0909 |
| 성동구   | 알뜰주유소   |       1714.0909 |
| 성동구   | S-OIL        |       1714.0909 |
| 성동구   | GS칼텍스     |       1714.0909 |
| 성동구   | 현대오일뱅크 |       1714.0909 |
| 성동구   | SK에너지     |       1714.0909 |
| 강동구   | 자가상표     |       1714.5000 |
| 강동구   | 알뜰주유소   |       1714.5000 |
| 강동구   | S-OIL        |       1714.5000 |
| 강동구   | GS칼텍스     |       1714.5000 |
| 강동구   | 현대오일뱅크 |       1714.5000 |
| 강동구   | SK에너지     |       1714.5000 |
| 종로구   | 자가상표     |       1804.0000 |
| 종로구   | 알뜰주유소   |       1804.0000 |
| 종로구   | S-OIL        |       1804.0000 |
| 종로구   | GS칼텍스     |       1804.0000 |
| 종로구   | 현대오일뱅크 |       1804.0000 |
| 종로구   | SK에너지     |       1804.0000 |
| 강남구   | 자가상표     |       1860.8065 |
| 강남구   | 알뜰주유소   |       1860.8065 |
| 강남구   | S-OIL        |       1860.8065 |
| 강남구   | GS칼텍스     |       1860.8065 |
| 강남구   | 현대오일뱅크 |       1860.8065 |
| 강남구   | SK에너지     |       1860.8065 |
| 중구     | 자가상표     |       1986.8571 |
| 중구     | 알뜰주유소   |       1986.8571 |
| 중구     | S-OIL        |       1986.8571 |
| 중구     | GS칼텍스     |       1986.8571 |
| 중구     | 현대오일뱅크 |       1986.8571 |
| 중구     | SK에너지     |       1986.8571 |
| 용산구   | 자가상표     |       2111.2727 |
| 용산구   | 알뜰주유소   |       2111.2727 |
| 용산구   | S-OIL        |       2111.2727 |
| 용산구   | GS
```칼텍스     |       2111.2727 |
| 용산구   | 현대오일뱅크 |       2111.2727 |
| 용산구   | SK에너지     |       2111.2727 |
+----------+--------------+-----------------+

In [131]:
sql = 'SELECT s.gu, b.name, avg(s.gasoline) FROM GAS_BRAND as b ,GAS_STATION as s GROUP BY s.gu, b.name order by avg(gasoline);'

In [132]:
conn = mysql.connector.connect(
    host = 'database-1.cfc20ugqgb4j.ap-northeast-2.rds.amazonaws.com',
    port = 3306,
    user = 'oneday',
    password = '1234',
    database = 'oneday'
)
cursor = conn.cursor(buffered=True)

In [133]:
cursor.execute(sql)

result = cursor.fetchall()
for row in result:
    print(row)

('도봉구', '자가상표', Decimal('1539.4286'))
('도봉구', '알뜰주유소', Decimal('1539.4286'))
('도봉구', 'S-OIL', Decimal('1539.4286'))
('도봉구', 'GS칼텍스', Decimal('1539.4286'))
('도봉구', '현대오일뱅크', Decimal('1539.4286'))
('도봉구', 'SK에너지', Decimal('1539.4286'))
('은평구', '자가상표', Decimal('1542.3333'))
('은평구', '알뜰주유소', Decimal('1542.3333'))
('은평구', 'S-OIL', Decimal('1542.3333'))
('은평구', 'GS칼텍스', Decimal('1542.3333'))
('은평구', '현대오일뱅크', Decimal('1542.3333'))
('은평구', 'SK에너지', Decimal('1542.3333'))
('중랑구', '자가상표', Decimal('1543.2727'))
('중랑구', '알뜰주유소', Decimal('1543.2727'))
('중랑구', 'S-OIL', Decimal('1543.2727'))
('중랑구', 'GS칼텍스', Decimal('1543.2727'))
('중랑구', '현대오일뱅크', Decimal('1543.2727'))
('중랑구', 'SK에너지', Decimal('1543.2727'))
('강북구', '자가상표', Decimal('1545.9000'))
('강북구', '알뜰주유소', Decimal('1545.9000'))
('강북구', 'S-OIL', Decimal('1545.9000'))
('강북구', 'GS칼텍스', Decimal('1545.9000'))
('강북구', '현대오일뱅크', Decimal('1545.9000'))
('강북구', 'SK에너지', Decimal('1545.9000'))
('성북구', '자가상표', Decimal('1553.6250'))
('성북구', '알뜰주유소', Decimal('1553.6250'))
('성북구', 'S-OIL', Decimal('1553.6250'))
('성북구', 'GS칼텍스', Decimal('1553.6250'))
('성북구', '현대오일뱅크', Decimal('1553.6250'))
('성북구', 'SK에너지', Decimal('1553.6250'))
('양천구', '자가상표', Decimal('1564.8500'))
('양천구', '알뜰주유소', Decimal('1564.8500'))
('양천구', 'S-OIL', Decimal('1564.8500'))
('양천구', 'GS칼텍스', Decimal('1564.8500'))
('양천구', '현대오일뱅크', Decimal('1564.8500'))
('양천구', 'SK에너지', Decimal('1564.8500'))
('금천구', '자가상표', Decimal('1570.6250'))
('금천구', '알뜰주유소', Decimal('1570.6250'))
('금천구', 'S-OIL', Decimal('1570.6250'))
('금천구', 'GS칼텍스', Decimal('1570.6250'))
('금천구', '현대오일뱅크', Decimal('1570.6250'))
('금천구', 'SK에너지', Decimal('1570.6250'))
('서대문구', '자가상표', Decimal('1571.7692'))
('서대문구', '알뜰주유소', Decimal('1571.7692'))
('서대문구', 'S-OIL', Decimal('1571.7692'))
('서대문구', 'GS칼텍스', Decimal('1571.7692'))
('서대문구', '현대오일뱅크', Decimal('1571.7692'))
('서대문구', 'SK에너지', Decimal('1571.7692'))
('동대문구', '자가상표', Decimal('1571.9286'))
('동대문구', '알뜰주유소', Decimal('1571.9286'))
('동대문구', 'S-OIL', Decimal('1571.9286'))
('동대문구', 'GS칼텍스', Decimal('1571.9286'))
('동대문구', '현대오일뱅크', Decimal('1571.9286'))
('동대문구', 'SK에너지', Decimal('1571.9286'))
('노원구', '자가상표', Decimal('1573.6154'))
('노원구', '알뜰주유소', Decimal('1573.6154'))
('노원구', 'S-OIL', Decimal('1573.6154'))
('노원구', 'GS칼텍스', Decimal('1573.6154'))
('노원구', '현대오일뱅크', Decimal('1573.6154'))
('노원구', 'SK에너지', Decimal('1573.6154'))
('구로구', '자가상표', Decimal('1577.8125'))
('구로구', '알뜰주유소', Decimal('1577.8125'))
('구로구', 'S-OIL', Decimal('1577.8125'))
('구로구', 'GS칼텍스', Decimal('1577.8125'))
('구로구', '현대오일뱅크', Decimal('1577.8125'))
('구로구', 'SK에너지', Decimal('1577.8125'))
('강서구', '자가상표', Decimal('1595.6667'))
('강서구', '알뜰주유소', Decimal('1595.6667'))
('강서구', 'S-OIL', Decimal('1595.6667'))
('강서구', 'GS칼텍스', Decimal('1595.6667'))
('강서구', '현대오일뱅크', Decimal('1595.6667'))
('강서구', 'SK에너지', Decimal('1595.6667'))
('광진구', '자가상표', Decimal('1595.7273'))
('광진구', '알뜰주유소', Decimal('1595.7273'))
('광진구', 'S-OIL', Decimal('1595.7273'))
('광진구', 'GS칼텍스', Decimal('1595.7273'))
('광진구', '현대오일뱅크', Decimal('1595.7273'))
('광진구', 'SK에너지', Decimal('1595.7273'))
('송파구', '자가상표', Decimal('1597.3333'))
('송파구', '알뜰주유소', Decimal('1597.3333'))
('송파구', 'S-OIL', Decimal('1597.3333'))
('송파구', 'GS칼텍스', Decimal('1597.3333'))
('송파구', '현대오일뱅크', Decimal('1597.3333'))
('송파구', 'SK에너지', Decimal('1597.3333'))
('마포구', '자가상표', Decimal('1600.0000'))
('마포구', '알뜰주유소', Decimal('1600.0000'))
('마포구', 'S-OIL', Decimal('1600.0000'))
('마포구', 'GS칼텍스', Decimal('1600.0000'))
('마포구', '현대오일뱅크', Decimal('1600.0000'))
('마포구', 'SK에너지', Decimal('1600.0000'))
('동작구', '자가상표', Decimal('1601.2857'))
('동작구', '알뜰주유소', Decimal('1601.2857'))
('동작구', 'S-OIL', Decimal('1601.2857'))
('동작구', 'GS칼텍스', Decimal('1601.2857'))
('동작구', '현대오일뱅크', Decimal('1601.2857'))
('동작구', 'SK에너지', Decimal('1601.2857'))
('관악구', '자가상표', Decimal('1605.0000'))
('관악구', '알뜰주유소', Decimal('1605.0000'))
('관악구', 'S-OIL', Decimal('1605.0000'))
('관악구', 'GS칼텍스', Decimal('1605.0000'))
('관악구', '현대오일뱅크', Decimal('1605.0000'))
('관악구', 'SK에너지', Decimal('1605.0000'))
('영등포구', '자가상표', Decimal('1636.9130'))
('영등포구', '알뜰주유소', Decimal('1636.9130'))
('영등포구', 'S-OIL', Decimal('1636.9130'))
('영등포구', 'GS칼텍스', Decimal('1636.9130'))
('영등포구', '현대오일뱅크', Decimal('1636.9130'))
('영등포구', 'SK에너지', Decimal('1636.9130'))
('서초구', '자가상표', Decimal('1665.1200'))
('서초구', '알뜰주유소', Decimal('1665.1200'))
('서초구', 'S-OIL', Decimal('1665.1200'))
('서초구', 'GS칼텍스', Decimal('1665.1200'))
('서초구', '현대오일뱅크', Decimal('1665.1200'))
('서초구', 'SK에너지', Decimal('1665.1200'))
('성동구', '자가상표', Decimal('1714.0909'))
('성동구', '알뜰주유소', Decimal('1714.0909'))
('성동구', 'S-OIL', Decimal('1714.0909'))
('성동구', 'GS칼텍스', Decimal('1714.0909'))
('성동구', '현대오일뱅크', Decimal('1714.0909'))
('성동구', 'SK에너지', Decimal('1714.0909'))
('강동구', '자가상표', Decimal('1714.5000'))
('강동구', '알뜰주유소', Decimal('1714.5000'))
('강동구', 'S-OIL', Decimal('1714.5000'))
('강동구', 'GS칼텍스', Decimal('1714.5000'))
('강동구', '현대오일뱅크', Decimal('1714.5000'))
('강동구', 'SK에너지', Decimal('1714.5000'))
('종로구', '자가상표', Decimal('1804.0000'))
('종로구', '알뜰주유소', Decimal('1804.0000'))
('종로구', 'S-OIL', Decimal('1804.0000'))
('종로구', 'GS칼텍스', Decimal('1804.0000'))
('종로구', '현대오일뱅크', Decimal('1804.0000'))
('종로구', 'SK에너지', Decimal('1804.0000'))
('강남구', '자가상표', Decimal('1860.8065'))
('강남구', '알뜰주유소', Decimal('1860.8065'))
('강남구', 'S-OIL', Decimal('1860.8065'))
('강남구', 'GS칼텍스', Decimal('1860.8065'))
('강남구', '현대오일뱅크', Decimal('1860.8065'))
('강남구', 'SK에너지', Decimal('1860.8065'))
('중구', '자가상표', Decimal('1986.8571'))
('중구', '알뜰주유소', Decimal('1986.8571'))
('중구', 'S-OIL', Decimal('1986.8571'))
('중구', 'GS칼텍스', Decimal('1986.8571'))
('중구', '현대오일뱅크', Decimal('1986.8571'))
('중구', 'SK에너지', Decimal('1986.8571'))
('용산구', '자가상표', Decimal('2111.2727'))
('용산구', '알뜰주유소', Decimal('2111.2727'))
('용산구', 'S-OIL', Decimal('2111.2727'))
('용산구', 'GS칼텍스', Decimal('2111.2727'))
('용산구', '현대오일뱅크', Decimal('2111.2727'))
('용산구', 'SK에너지', Decimal('2111.2727'))

In [134]:
conn.close()

---